/*******************************************************************************
 * OnlinePartyChatInterface generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
interface OnlinePartyChatInterface extends Interface
    abstract;

function bool SendPartyGameInvites(byte LocalUserNum);

delegate OnSendPartyGameInvitesComplete(bool bWasSuccessful);

function AddSendPartyGameInvitesCompleteDelegate(byte LocalUserNum, delegate<OnSendPartyGameInvitesComplete> SendPartyGameInvitesCompleteDelegate);

function ClearSendPartyGameInvitesCompleteDelegate(byte LocalUserNum, delegate<OnSendPartyGameInvitesComplete> SendPartyGameInvitesCompleteDelegate);

function bool GetPartyMembersInformation(out array<OnlinePartyMember> PartyMembers);

function bool GetPartyMemberInformation(UniqueNetId MemberId, out OnlinePartyMember PartyMember);

delegate OnPartyMemberListChanged(bool bJoinedOrLeft, string PlayerName, UniqueNetId PlayerID);

function AddPartyMemberListChangedDelegate(byte LocalUserNum, delegate<OnPartyMemberListChanged> PartyMemberListChangedDelegate);

function ClearPartyMemberListChangedDelegate(byte LocalUserNum, delegate<OnPartyMemberListChanged> PartyMemberListChangedDelegate);

delegate OnReservedPartyMemberListChanged(bool bJoinedOrLeft, string PlayerName, UniqueNetId PlayerID);

function AddReservedPartyMemberListChangedDelegate(byte LocalUserNum, delegate<OnReservedPartyMemberListChanged> ReservedPartyMemberListChangedDelegate);

function ClearReservedPartyMemberListChangedDelegate(byte LocalUserNum, delegate<OnReservedPartyMemberListChanged> ReservedPartyMemberListChangedDelegate);

delegate OnPartyMembersInfoChanged(string PlayerName, UniqueNetId PlayerID, int CustomData1, int CustomData2, int CustomData3, int CustomData4);

function AddPartyMembersInfoChangedDelegate(byte LocalUserNum, delegate<OnPartyMembersInfoChanged> PartyMembersInfoChangedDelegate);

function ClearPartyMembersInfoChangedDelegate(byte LocalUserNum, delegate<OnPartyMembersInfoChanged> PartyMembersInfoChangedDelegate);

function bool SetPartyMemberCustomData(byte LocalUserNum, int Data1, int Data2, int Data3, int Data4);

function int GetPartyBandwidth();

function bool ShowPartyUI(byte LocalUserNum);

function bool ShowVoiceChannelUI(byte LocalUserNum);

function bool ShowCommunitySessionsUI(byte LocalUserNum);

function bool IsInPartyChat(byte LocalUserNum);
