/*******************************************************************************
 * PointLightComponent generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class PointLightComponent extends LightComponent
    native(Light)
    editinlinenew
    hidecategories(Object);

var float ShadowRadiusMultiplier;
var() interp float Radius<UIMin=8.0|UIMax=1024.0>;
/** Controls the radial falloff of the light */
var() interp float FalloffExponent;
/** falloff for shadow when using LightShadow_Modulate */
var() float ShadowFalloffExponent;
var float MinShadowFalloffRadius;
var const Matrix CachedParentToWorld;
var() const Vector Translation;
var const Plane ShadowPlane;
var const export editinline DrawLightRadiusComponent PreviewLightRadius;
/** The Lightmass settings for this object. */
var(Lightmass) LightmassPointLightSettings LightmassSettings<ScriptOrder=true>;
var const export editinline DrawLightRadiusComponent PreviewLightSourceRadius;
var export editinline SpriteComponent LightSprite;
/** (TW) NPCs using the PreferDarkness path constraint won't take this pointlight into consideration */
var() bool bAIIgnoreLuminosity;

// Export UPointLightComponent::execSetTranslation(FFrame&, void* const)
native final function SetTranslation(Vector NewTranslation);

// Export UPointLightComponent::execSetRadius(FFrame&, void* const)
native final function SetRadius(float NewRadius);

function OnUpdatePropertyLightColor()
{
    UpdateColorAndBrightness();
}

function OnUpdatePropertyBrightness()
{
    UpdateColorAndBrightness();
}

defaultproperties
{
    ShadowRadiusMultiplier=1.1
    Radius=1024
    FalloffExponent=2
    ShadowFalloffExponent=2
    ShadowPlane=(W=0,X=0,Y=0,Z=1)
    LightmassSettings=(LightSourceRadius=100,IndirectLightingScale=1,IndirectLightingSaturation=1,ShadowExponent=2)
    bCastPerObjectShadows=true
}