/*******************************************************************************
 * KFDT_Piercing generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KFDT_Piercing extends KFDamageType
    abstract;

static simulated function bool CanDismemberHitZone(name InHitZoneName)
{
    switch(InHitZoneName)
    {
        case 'lhand':
        case 'rhand':
        case 'lfoot':
        case 'rfoot':
        case 'lforearm':
        case 'rforearm':
        case 'lcalf':
        case 'rcalf':
        case 'lthigh':
        case 'rthigh':
        case 'head':
            return true;
        default:
            return false;
            break;
    }
}

defaultproperties
{
    EffectGroup=EEffectDamageGroup.FXG_Piercing
    KDamageImpulse=300
}