/*******************************************************************************
 * KFDT_Freeze generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KFDT_Freeze extends KFDamageType
    abstract;

var protected ParticleSystem FrozenShatterTemplate;
var protected AkBaseSoundObject ShatterSound;

static function int GetKillerDialogID()
{
    return 88;
}

static function int GetDamagerDialogID()
{
    return 103;
}

static function PlayShatter(KFPawn P, optional bool bSkipParticles, optional bool bMaterialOnly, optional Vector RBLinearVelocity)
{
    local KFPawn_Monster Zed;
    local KFGoreManager GoreManager;
    local float IceScalar;
    local int MICIndex, I, J;
    local MaterialInstanceConstant MIC;

    IceScalar = 1;
    if(!bMaterialOnly)
    {
        Zed = KFPawn_Monster(P);
        if((Zed != none) && !Zed.bUseDamageInflation)
        {
            GoreManager = KFGoreManager(P.WorldInfo.MyGoreEffectManager);
            if((GoreManager != none) && GoreManager.AllowMutilation())
            {
                if((Zed.bReinitPhysAssetOnDeath && Zed.CharacterArch != none) && Zed.CharacterArch.PhysAsset != none)
                {
                    Zed.bReinitPhysAssetOnDeath = false;
                    Zed.Mesh.SetPhysicsAsset(Zed.CharacterArch.PhysAsset,, true);
                }
                if(!Zed.bIsGoreMesh)
                {
                    Zed.SwitchToGoreMesh();
                }
                Zed.ForceBreakAllConstraints();                
            }
            else
            {
                IceScalar = 0.4;
            }
            if(!IsZero(RBLinearVelocity))
            {
                P.Mesh.SetRBLinearVelocity(RBLinearVelocity, true);
            }
        }
        if(!bSkipParticles)
        {
            P.WorldInfo.MyEmitterPool.SpawnEmitter(default.FrozenShatterTemplate, P.Location, rotator(vect(0, 0, 1)));
            P.PlaySoundBase(default.ShatterSound, true,,, P.Location);
        }
    }
    MICIndex = 0;
    if(P.GetCharacterInfo() != none)
    {
        MICIndex = P.GetCharacterInfo().GoreFXMICIdx;
    }
    if(P.CharacterMICs.Length > MICIndex)
    {
        P.CharacterMICs[MICIndex].SetScalarParameterValue('Scalar_Ice', IceScalar);
    }
    I = 0;
    J0x48E:

    if(I < 3)
    {
        if(P.ThirdPersonAttachments[I] != none)
        {
            J = 0;
            J0x4D7:

            if(J < P.ThirdPersonAttachments[I].Materials.Length)
            {
                MIC = MaterialInstanceConstant(P.ThirdPersonAttachments[I].GetMaterial(J));
                if(MIC != none)
                {
                    MIC.SetScalarParameterValue('Scalar_Ice', IceScalar);
                }
                ++ J;
                goto J0x4D7;
            }
        }
        ++ I;
        goto J0x48E;
    }
}

defaultproperties
{
    FrozenShatterTemplate=ParticleSystem'WEP_Freeze_Grenade_EMIT.FX_Freeze_Grenade_Death'
    ShatterSound=AkEvent'WW_WEP_Freeze_Grenade.Play_Freeze_Grenade_Shatter'
    FreezePower=2.5
}