/*******************************************************************************
 * KFGFxHUD_ObjectiveConatiner generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KFGFxHUD_ObjectiveConatiner extends GFxObject within GFxMoviePlayer;

var float UpdateRate;
var KFInterface_MapObjective CurrentObjectiveInterface;
var Texture2D LastIcon;
var KFPlayerController KFPC;
var name SoundThemeName;
var name SoundCueName;
var float LastProgress;
var bool bLastMissionCritical;

function InitializeHUD()
{
    KFPC = KFPlayerController(Outer.GetPC());
    SetVisible(false);
    LocalizeContainer();
}

function LocalizeContainer()
{
    local GFxObject TextObject;

    TextObject = Outer.CreateObject("Object");
    if(NotEqual_InterfaceInterface(CurrentObjectiveInterface, (none)))
    {
        TextObject.SetString("failedString", Localize("Objectives", "FailedString", "KFGame"));
        TextObject.SetString("objectiveTitle", Localize("Objectives", "ObjectiveTitle", "KFGame"));
        TextObject.SetString("objectiveDesc", CurrentObjectiveInterface.GetLocalizedShortDescription());
    }
    SetObject("localizedText", TextObject);
}

simulated function SetActive(bool bActive)
{
    SetVisible(bActive);
    if(bActive)
    {
        CurrentObjectiveInterface = KFGameReplicationInfo(Outer.GetPC().WorldInfo.GRI).ObjectiveInterface;
        if(NotEqual_InterfaceInterface(CurrentObjectiveInterface, (none)) && CurrentObjectiveInterface.ShouldShowObjectiveContainer())
        {
            SetFailState(CurrentObjectiveInterface.HasFailedObjective());
            SetCurrentProgress(CurrentObjectiveInterface.GetProgress());
            LocalizeContainer();
            UpdateIcon();
            SetCompleted(CurrentObjectiveInterface.IsComplete());
            SetMissionCritical(CurrentObjectiveInterface.GetIsMissionCritical());            
        }
        else
        {
            CurrentObjectiveInterface = none;
            SetVisible(false);
        }        
    }
    else
    {
        CurrentObjectiveInterface = none;
        GetObject("objectiveNumberMC").SetVisible(false);
    }
}

function SetCompleted(bool bComplete)
{
    local GFxObject DataObject;

    DataObject = Outer.CreateObject("Object");
    DataObject.SetBool("bComplete", bComplete);
    DataObject.SetString("completeString", ((bComplete) ? Localize("Objectives", "SuccessString", "KFGame") : ""));
    SetObject("completeStatus", DataObject);
    if(((KFPC != none) && KFPC.myGfxHUD != none) && bComplete)
    {
        KFPC.myGfxHUD.PlaySoundFromTheme(SoundCueName, SoundThemeName);
    }
}

function SetMissionCritical(bool bMissionCritical)
{
    bMissionCritical = false;
    if(bMissionCritical != bLastMissionCritical)
    {
        SetBool("missionCriticalStatus", bMissionCritical);
        bLastMissionCritical = bMissionCritical;
    }
}

function SetCurrentIcon(string IconPath)
{
    if(IconPath == "")
    {
        SetString("currentIcon", "");        
    }
    else
    {
        SetString("currentIcon", "img://" $ IconPath);
    }
}

function TickHud(float DeltaTime)
{
    local int bStatusWarning, bStatusNotification;
    local string StatusMessage;
    local GFxObject DataObject;

    if(NotEqual_InterfaceInterface(CurrentObjectiveInterface, (none)))
    {
        if(!CurrentObjectiveInterface.HasFailedObjective() && !CurrentObjectiveInterface.IsComplete())
        {
            SetString("currentProgressText", CurrentObjectiveInterface.GetProgressText());
        }
        CurrentObjectiveInterface.GetLocalizedStatus(StatusMessage, bStatusWarning, bStatusNotification);
        DataObject = Outer.CreateObject("Object");
        DataObject.SetBool("bStatusWarning", bool(bStatusWarning));
        DataObject.SetBool("bStatusNotification", bool(bStatusNotification));
        DataObject.SetString("StatusMessage", StatusMessage);
        SetObject("currentStatus", DataObject);
        SetInt("rewardValue", CurrentObjectiveInterface.GetDoshReward());
        SetCurrentProgress(CurrentObjectiveInterface.GetProgress());
        SetFailState(CurrentObjectiveInterface.HasFailedObjective());
        if(LastIcon != CurrentObjectiveInterface.GetIcon())
        {
            UpdateIcon();
        }
        SetMissionCritical(CurrentObjectiveInterface.GetIsMissionCritical());
    }
}

function UpdateIcon()
{
    LastIcon = CurrentObjectiveInterface.GetIcon();
    SetCurrentIcon(PathName(LastIcon));
}

function UpdateRequirements();

function SetFailState(bool bFailed)
{
    local GFxObject DataObject;

    DataObject = Outer.CreateObject("Object");
    DataObject.SetBool("bFailed", bFailed);
    DataObject.SetString("failedString", ((bFailed) ? Localize("Objectives", "FailedString", "KFGame") : ""));
    SetObject("failed", DataObject);
    if(bFailed)
    {
    }
}

function ClearObjectiveUI()
{
    SetActive(false);
}

function SetCurrentProgress(float CurrentProgress)
{
    if(LastProgress != CurrentProgress)
    {
        CurrentProgress = FClamp(CurrentProgress, 0, 1);
        LastProgress = CurrentProgress;
        SetInt("currentProgress", int(float(100) * CurrentProgress));
        SetCompleted(CurrentObjectiveInterface.IsComplete());
    }
}

defaultproperties
{
    UpdateRate=0.1
    SoundThemeName=UI
    SoundCueName=TraderTime_Countdown
}