/*******************************************************************************
 * KFGFxPerksContainer_Details generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KFGFxPerksContainer_Details extends KFGFxPerksContainer within GFxMoviePlayer;

var const localized string ExperienceString;
var const localized string ObjectivesString;
var const localized string PerkBonusesString;
var const localized string BasicLoadoutString;

function Initialize(KFGFxObject_Menu NewParentMenu)
{
    super(KFGFxObject_Container).Initialize(NewParentMenu);
    LocalizeContainer();
}

function LocalizeContainer()
{
    GetObject("objectivesTitleTextField").SetString("text", ObjectivesString);
    GetObject("perkBonusTextField").SetString("text", PerkBonusesString);
    GetObject("basicLoadoutTextField").SetString("text", BasicLoadoutString);
}

function UpdateDetails(class<KFPerk> PerkClass)
{
    local GFxObject DetailsProvider;
    local KFPlayerController KFPC;
    local KFGameReplicationInfo KFGRI;
    local array<string> WeaponNames, WeaponSources;
    local string WeaponNameStringHolder, WeaponSourceStringHolder;
    local int I;

    DetailsProvider = Outer.CreateObject("Object");
    KFPC = KFPlayerController(Outer.GetPC());
    if(KFPC != none)
    {
        KFGRI = KFGameReplicationInfo(KFPC.WorldInfo.GRI);
        if(KFPC != none)
        {
            DetailsProvider.SetString("ExperienceMessage", ExperienceString @ string(KFPC.GetPerkXP(PerkClass)));
        }
        if(KFGRI != none)
        {
            if(PerkClass.default.PrimaryWeaponClassName != "")
            {
                KFGRI.TraderItems.GetItemInfo(PerkClass, PerkClass.default.PrimaryWeaponClassName, WeaponNameStringHolder, WeaponSourceStringHolder);
                AddWeaponInfo(WeaponNames, WeaponSources, WeaponNameStringHolder, WeaponSourceStringHolder);
            }
            if(Class'KFPerk'.default.SecondaryWeaponClassName != "")
            {
                KFGRI.TraderItems.GetItemInfo(PerkClass, PerkClass.default.SecondaryWeaponClassName, WeaponNameStringHolder, WeaponSourceStringHolder);
                AddWeaponInfo(WeaponNames, WeaponSources, WeaponNameStringHolder, WeaponSourceStringHolder);
            }
            if(PerkClass.default.MeleeWeaponClassName != "")
            {
                KFGRI.TraderItems.GetItemInfo(PerkClass, PerkClass.default.MeleeWeaponClassName, WeaponNameStringHolder, WeaponSourceStringHolder);
                AddWeaponInfo(WeaponNames, WeaponSources, WeaponNameStringHolder, WeaponSourceStringHolder);
            }
            if(PerkClass.default.GrenadeClassName != "")
            {
                KFGRI.TraderItems.GetGrenadeItemInfo(PerkClass, PerkClass.default.GrenadeClassName, WeaponNameStringHolder, WeaponSourceStringHolder);
                AddWeaponInfo(WeaponNames, WeaponSources, WeaponNameStringHolder, WeaponSourceStringHolder);
            }
        }
        I = 0;
        J0x44B:

        if(I < WeaponNames.Length)
        {
            DetailsProvider.SetString("WeaponName" $ string(I), WeaponNames[I]);
            DetailsProvider.SetString("WeaponImage" $ string(I), "img://" $ WeaponSources[I]);
            ++ I;
            goto J0x44B;
        }
        DetailsProvider.SetString("EXPAction1", PerkClass.default.EXPAction1);
        DetailsProvider.SetString("EXPAction2", PerkClass.default.EXPAction2);
        SetObject("detailsData", DetailsProvider);
    }
}

function AddWeaponInfo(out array<string> WeaponNames, out array<string> WeaponSources, string WeaponName, string WeaponSource)
{
    WeaponNames.AddItem(WeaponName;
    WeaponSources.AddItem(WeaponSource;
}

function UpdatePassives(class<KFPerk> PerkClass)
{
    local GFxObject PassivesProvider, PassiveObject;
    local KFPlayerController KFPC;
    local array<string> PassiveValues, Increments;
    local byte I;

    KFPC = KFPlayerController(Outer.GetPC());
    if(KFPC != none)
    {
        PerkClass.static.GetPassiveStrings(PassiveValues, Increments, KFPC.GetPerkLevelFromPerkList(PerkClass));
        PassivesProvider = Outer.CreateArray();
        I = 0;
        J0xCF:

        if(I < PassiveValues.Length)
        {
            PassiveObject = Outer.CreateObject("Object");
            PassiveObject.SetString("PassiveTitle", PerkClass.default.Passives[I].Title);
            PassiveObject.SetString("PerkBonusModifier", Increments[I]);
            PassiveObject.SetString("PerkBonusAmount", PassiveValues[I]);
            PassivesProvider.SetElementObject(I, PassiveObject);
            ++ I;
            goto J0xCF;
        }
    }
    SetObject("passivesData", PassivesProvider);
}

defaultproperties
{
    ObjectivesString="XP OBJECTIVES"
    PerkBonusesString="PERK BONUSES"
    BasicLoadoutString="STARTING LOADOUT"
}