/*******************************************************************************
 * KFWeapDef_MP5RAS generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KFWeapDef_MP5RAS extends KFWeaponDefinition
    abstract;

defaultproperties
{
    WeaponClassPath="KFGameContent.KFWeap_SMG_MP5RAS"
    ImagePath="WEP_UI_MP5RAS_TEX.UI_WeaponSelect_MP5RAS"
    BuyPrice=650
    AmmoPricePerMag=33
    EffectiveRange=70
}