/*******************************************************************************
 * KFWeapDef_Zweihander generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KFWeapDef_Zweihander extends KFWeaponDefinition
    abstract;

defaultproperties
{
    WeaponClassPath="KFGameContent.KFWeap_Edged_Zweihander"
    ImagePath="WEP_UI_Zweihander_TEX.UI_WeaponSelect_Zweihander"
    BuyPrice=1000
    SharedUnlockId=ESharedContentUnlock.SCU_Zweihander
    EffectiveRange=3
}