/*******************************************************************************
 * KFWeapDef_AF2011 generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KFWeapDef_AF2011 extends KFWeaponDefinition
    abstract;

defaultproperties
{
    WeaponClassPath="KFGameContent.KFWeap_Pistol_AF2011"
    ImagePath="WEP_UI_AF2001_TEX.UI_WeaponSelect_AF2011"
    BuyPrice=750
    AmmoPricePerMag=27
    UpgradePrice(0)=1500
    UpgradeSellPrice(0)=1125
    EffectiveRange=50
}