class KFTraderVoiceGroup_Default extends KFTraderVoiceGroupBase;

`include(KFGame/KFGameDialog.uci)

DefaultProperties
{
	DialogEvents[`TRAD_FirstWave]=					(EventID=`TRAD_FirstWave,				AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COM_FirstWave',		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_LastManStanding]=           	(EventID=`TRAD_LastManStanding,			AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COM_TeamLastOne',	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_Wave20pctDead]=           	(EventID=`TRAD_Wave20pctDead,			AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COM_20ZedDead', 		Priority=1, Chance=0.3f,  CoolDown=0.f)
	DialogEvents[`TRAD_Wave80pctDead]=           	(EventID=`TRAD_Wave80pctDead,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COM_80ZedDead', 		Priority=1, Chance=0.3f,  CoolDown=0.f)
	DialogEvents[`TRAD_WaveLastZedDies]=         	(EventID=`TRAD_WaveLastZedDies,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COM_LastZedDead', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_Close]=                   	(EventID=`TRAD_Close,	                AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COM_ShopClose', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_PlayerArrive]=            	(EventID=`TRAD_PlayerArrive,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_SHOP_PlayerArrives', Priority=0, Chance=0.3f,  CoolDown=0.f)
	DialogEvents[`TRAD_ClickTooExpensive]=       	(EventID=`TRAD_ClickTooExpensive,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_SHOP_TooExp', 		Priority=0, CoolDown=0.f)
	DialogEvents[`TRAD_ClickTooHeavy]=           	(EventID=`TRAD_ClickTooHeavy,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_SHOP_TooHeavy', 		Priority=0, CoolDown=0.f)
	DialogEvents[`TRAD_30SecLeft]=               	(EventID=`TRAD_30SecLeft,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_SHOP_30Seconds', 	Priority=0, Chance=0.4f,  CoolDown=0.f)
	DialogEvents[`TRAD_10SecLeft]=               	(EventID=`TRAD_10SecLeft,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_SHOP_10Seconds', 	Priority=0, CoolDown=0.f)
	DialogEvents[`TRAD_FinalShopWave]=           	(EventID=`TRAD_FinalShopWave,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_SHOP_LastShop', 		Priority=0, CoolDown=0.f)
	DialogEvents[`TRAD_PlayerFarAway]=           	(EventID=`TRAD_PlayerFarAway,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_SHOP_LongRun', 		Priority=1, CoolDown=10.f)
	DialogEvents[`TRAD_NoArmor]=                 	(EventID=`TRAD_NoArmor,	                AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_SHOP_NoArmor', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_LowArmor]=                	(EventID=`TRAD_LowArmor,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_SHOP_LowArmor', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_LowAmmo]=                 	(EventID=`TRAD_LowAmmo,	                AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_SHOP_LowAmmo', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_NoNades]=                 	(EventID=`TRAD_NoNades,	                AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_SHOP_NoNades', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_NeedToHeal]=              	(EventID=`TRAD_NeedToHeal,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_SHOP_Heal', 			Priority=1, Chance=0.25f,  CoolDown=10.f)
	DialogEvents[`TRAD_TeamNeedsHeal]=           	(EventID=`TRAD_TeamNeedsHeal,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_SHOP_TeamHeal', 		Priority=1, Chance=0.25f,  CoolDown=10.f)
	DialogEvents[`TRAD_ShareDosh]=               	(EventID=`TRAD_ShareDosh,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_SHOP_RichBastard', 	Priority=1, CoolDown=0.f) // Rich Bastard???????
	DialogEvents[`TRAD_GoodJobHeal]=             	(EventID=`TRAD_GoodJobHeal,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_POST_GoodHealing', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_OnlySurvivor]=            	(EventID=`TRAD_OnlySurvivor,	 		AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_POST_SoleSurv', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_DiedLastWave]=            	(EventID=`TRAD_DiedLastWave,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_POST_Died', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_KilledMost]=              	(EventID=`TRAD_KilledMost,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_POST_KillMost', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_BestTeamPlayer]=          	(EventID=`TRAD_BestTeamPlayer,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_POST_TeamPlayer', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_SurviveMultWaves]=        	(EventID=`TRAD_SurviveMultWaves,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_POST_SurvRounds',	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_KeepDying]=               	(EventID=`TRAD_KeepDying,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_POST_DiedRounds', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_NoOneDies]=               	(EventID=`TRAD_NoOneDies,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_POST_NooneDied', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_NoDamage]=                	(EventID=`TRAD_NoDamage,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_POST_NoDamage', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_SomeDie]=                 	(EventID=`TRAD_SomeDie,	                AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_POST_SomeDied', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_LT50pctDamTaken]=         	(EventID=`TRAD_LT50pctDamTaken,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_POST_50Better', 		Priority=1, Chance=0.5f,   CoolDown=0.f)
	DialogEvents[`TRAD_HighDmgSurvivor]=         	(EventID=`TRAD_HighDmgSurvivor,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_POST_LotDamage', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_HighDmgHighHeal]=         	(EventID=`TRAD_HighDmgHighHeal,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_POST_LotDamLotHeal', Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_EarnMostDosh]=            	(EventID=`TRAD_EarnMostDosh,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_POST_MostDosh', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_KilledFleshpound]=        	(EventID=`TRAD_KilledFleshpound,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_POST_KillFP', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_KilledScrake]=            	(EventID=`TRAD_KilledScrake,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_POST_KillScrake', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_LittleDosh]=              	(EventID=`TRAD_LittleDosh,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_POST_LowDosh', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_AdviceClotA]=             	(EventID=`TRAD_AdviceClotA,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ADVC_ClotA', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_AdviceClotU]=             	(EventID=`TRAD_AdviceClotU,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ADVC_ClotU', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_AdviceClotS]=             	(EventID=`TRAD_AdviceClotS,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ADVC_ClotS', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_AdviceGorefast]=          	(EventID=`TRAD_AdviceGorefast,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ADVC_Gore1', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_AdviceGorefast2]=         	(EventID=`TRAD_AdviceGorefast2,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ADVC_Gore2', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_AdviceStalker]=           	(EventID=`TRAD_AdviceStalker,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ADVC_Stalk', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_AdviceBloat]=             	(EventID=`TRAD_AdviceBloat,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ADVC_Bloat', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_AdviceScrake]=            	(EventID=`TRAD_AdviceScrake,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ADVC_Scrake', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_AdviceFleshpound]=        	(EventID=`TRAD_AdviceFleshpound,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ADVC_FP', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_AdviceSiren]=             	(EventID=`TRAD_AdviceSiren,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ADVC_Siren', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_AdviceHusk]=              	(EventID=`TRAD_AdviceHusk,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ADVC_Husk', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_AdvicePatriarch]=         	(EventID=`TRAD_AdvicePatriarch,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ADVC_Patty', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_AdviceHans]=              	(EventID=`TRAD_AdviceHans,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ADVC_Hans', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_AdviceMatriarch]=         	(EventID=`TRAD_AdviceMatriarch,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ADVC_Matty', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendT]=              	(EventID=`TRAD_ObjDefendT,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEF1_Target', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendTWon]=           	(EventID=`TRAD_ObjDefendTWon,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEF1_Won', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendTDeclined]=      	(EventID=`TRAD_ObjDefendTDeclined,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEF1_ObjDecl', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendTFailed]=        	(EventID=`TRAD_ObjDefendTFailed,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEF1_StartFail', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendTs]=             	(EventID=`TRAD_ObjDefendTs,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEF9_Target', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendTsWon]=          	(EventID=`TRAD_ObjDefendTsWon,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEF9_Won', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendTsDeclined]=     	(EventID=`TRAD_ObjDefendTsDeclined,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEF9_ObjDecl', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendTsFailed]=       	(EventID=`TRAD_ObjDefendTsFailed,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEF9_StartFail', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendA]=              	(EventID=`TRAD_ObjDefendA,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEFA_Area', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendAWon]=           	(EventID=`TRAD_ObjDefendAWon,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEFA_Won', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendADeclined]=      	(EventID=`TRAD_ObjDefendADeclined,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEFA_ObjDecl', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendAFailed]=        	(EventID=`TRAD_ObjDefendAFailed,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEFA_StartFail', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendAs]=             	(EventID=`TRAD_ObjDefendAs,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEFS_Areas', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendAsWon]=          	(EventID=`TRAD_ObjDefendAsWon,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEFS_Won', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendAsDeclined]=     	(EventID=`TRAD_ObjDefendAsDeclined,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEFS_ObjDecl', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendAsFailed]=       	(EventID=`TRAD_ObjDefendAsFailed,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEFS_StartFail', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjHackTerm]=             	(EventID=`TRAD_ObjHackTerm,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_HCK1_HackTerm', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjHackTermWon]=          	(EventID=`TRAD_ObjHackTermWon,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_HCK1_Won', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjHackTermDeclined]=     	(EventID=`TRAD_ObjHackTermDeclined,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_HCK1_ObjDecl', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjHackTermFailed]=       	(EventID=`TRAD_ObjHackTermFailed,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_HCK1_StartFail', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjHackTerms]=            	(EventID=`TRAD_ObjHackTerms,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_HCK9_HackTerms', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjHackTermsWon]=         	(EventID=`TRAD_ObjHackTermsWon,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_HCK9_Won', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjHackTermsDeclined]=    	(EventID=`TRAD_ObjHackTermsDeclined,	AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_HCK9_ObjDecl', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjHackTermsFailed]=      	(EventID=`TRAD_ObjHackTermsFailed,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_HCK9_StartFail', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDownload]=             	(EventID=`TRAD_ObjDownload,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DNLD_DownloadData', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDownloadWon]=          	(EventID=`TRAD_ObjDownloadWon,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DNLD_Won', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDownloadDeclined]=     	(EventID=`TRAD_ObjDownloadDeclined,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DNLD_ObjDecl', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDownloadFailed]=       	(EventID=`TRAD_ObjDownloadFailed,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DNLD_StartFail', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjRepairT]=              	(EventID=`TRAD_ObjRepairT,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_REP1_RepairTarget', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjRepairTWon]=           	(EventID=`TRAD_ObjRepairTWon,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_REP1_Won', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjRepairTDeclined]=      	(EventID=`TRAD_ObjRepairTDeclined,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_REP1_ObjDecl', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjRepairTFailed]=        	(EventID=`TRAD_ObjRepairTFailed,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_REP1_StartFail', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjRepairTs]=             	(EventID=`TRAD_ObjRepairTs,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_REP9_RepairTargets', Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjRepairTsWon]=          	(EventID=`TRAD_ObjRepairTsWon,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_REP9_Won', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjRepairTsDeclined]=     	(EventID=`TRAD_ObjRepairTsDeclined,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_REP9_ObjDecl', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjRepairTsFailed]=       	(EventID=`TRAD_ObjRepairTsFailed,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_REP9_StartFail', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjEscVIP]=               	(EventID=`TRAD_ObjEscVIP,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ESC1_VIP', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjEscVIPWon]=            	(EventID=`TRAD_ObjEscVIPWon,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ESC1_Won', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjEscVIPDeclined]=       	(EventID=`TRAD_ObjEscVIPDeclined,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ESC1_ObjDecl', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjEscVIPFailed]=         	(EventID=`TRAD_ObjEscVIPFailed,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ESC1_StartFail', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjEscVIPs]=              	(EventID=`TRAD_ObjEscVIPs,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ESC9_VIPs', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjEscVIPsWon]=           	(EventID=`TRAD_ObjEscVIPsWon,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ESC9_Won',			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjEscVIPsDeclined]=      	(EventID=`TRAD_ObjEscVIPsDeclined,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ESC9_ObjDecl', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjEscVIPsFailed]=        	(EventID=`TRAD_ObjEscVIPsFailed,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ESC9_StartFail', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjCollItem]=             	(EventID=`TRAD_ObjCollItem,	            AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COL1_Item', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjCollItemWon]=          	(EventID=`TRAD_ObjCollItemWon,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COL1_Won', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjCollItemDeclined]=     	(EventID=`TRAD_ObjCollItemDeclined,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COL1_ObjDecl', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjCollItemFailed]=       	(EventID=`TRAD_ObjCollItemFailed,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COL1_StartFail', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjCollItems]=            	(EventID=`TRAD_ObjCollItems,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COL9_Items', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjCollItemsWon]=         	(EventID=`TRAD_ObjCollItemsWon,	        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COL9_Won', 			Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjCollItemsDeclined]=    	(EventID=`TRAD_ObjCollItemsDeclined,	AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COL9_ObjDecl', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjCollItemsFailed]=      	(EventID=`TRAD_ObjCollItemsFailed,	    AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COL9_StartFail', 	Priority=1, CoolDown=0.f)

	DialogEvents[`TRAD_AdviceCrawler]=      		(EventID=`TRAD_AdviceCrawler,	    	AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ADVC_Crawler', 		Priority=1, CoolDown=0.f)

	DialogEvents[`TRAD_ObjDefendTFailedX]=			(EventID=`TRAD_ObjDefendTFailedX,		AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEF1_StartFailX', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendTWonJust]=			(EventID=`TRAD_ObjDefendTWonJust,		AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEF1_WonJust', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendTWonGood]=          (EventID=`TRAD_ObjDefendTWonGood,       AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEF1_WonGood', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendTWonPerf]=          (EventID=`TRAD_ObjDefendTWonPerf,       AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEF1_WonPerfect', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendTsFailedX]=			(EventID=`TRAD_ObjDefendTsFailedX,		AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEF9_StartFailX', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendTsWonJust]=         (EventID=`TRAD_ObjDefendTsWonJust,      AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEF9_WonJust', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendTsWonGood]=         (EventID=`TRAD_ObjDefendTsWonGood,      AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEF9_WonGood', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendTsWonPerf]=         (EventID=`TRAD_ObjDefendTsWonPerf,      AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEF9_WonPerfect', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendAFailedX]=			(EventID=`TRAD_ObjDefendAFailedX,		AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEFA_StartFailX', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendAWonJust]=          (EventID=`TRAD_ObjDefendAWonJust,       AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEFA_WonJust', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendAWonGood]=          (EventID=`TRAD_ObjDefendAWonGood,       AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEFA_WonGood', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendAWonPerf]=          (EventID=`TRAD_ObjDefendAWonPerf,       AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEFA_WonPerfect', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendAsFailedX]=			(EventID=`TRAD_ObjDefendAsFailedX,		AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEFS_StartFailX', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendAsWonJust]=         (EventID=`TRAD_ObjDefendAsWonJust,      AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEFS_WonJust', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendAsWonGood]=         (EventID=`TRAD_ObjDefendAsWonGood,      AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEFS_WonGood', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDefendAsWonPerf]=         (EventID=`TRAD_ObjDefendAsWonPerf,      AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DEFS_WonPerfect', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjHackTermFailedX]=			(EventID=`TRAD_ObjHackTermFailedX,		AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_HCK1_StartFailX', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjHackTermWonJust]=         (EventID=`TRAD_ObjHackTermWonJust,      AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_HCK1_WonJust', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjHackTermWonGood]=         (EventID=`TRAD_ObjHackTermWonGood,      AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_HCK1_WonGood', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjHackTermWonPerf]=         (EventID=`TRAD_ObjHackTermWonPerf,      AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_HCK1_WonPerfect', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjHackTermsFailedX]=		(EventID=`TRAD_ObjHackTermsFailedX,		AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_HCK9_StartFailX', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjHackTermsWonJust]=        (EventID=`TRAD_ObjHackTermsWonJust,     AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_HCK9_WonJust', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjHackTermsWonGood]=        (EventID=`TRAD_ObjHackTermsWonGood,     AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_HCK9_WonGood', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjHackTermsWonPerf]=        (EventID=`TRAD_ObjHackTermsWonPerf,     AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_HCK9_WonPerfect', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDownloadFailedX]=			(EventID=`TRAD_ObjDownloadFailedX,		AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DNLD_StartFailX', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDownloadWonJust]=         (EventID=`TRAD_ObjDownloadWonJust,      AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DNLD_WonJust', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDownloadWonGood]=         (EventID=`TRAD_ObjDownloadWonGood,      AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DNLD_WonGood', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjDownloadWonPerf]=         (EventID=`TRAD_ObjDownloadWonPerf,      AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_DNLD_WonPerfect', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjRepairTFailedX]=			(EventID=`TRAD_ObjRepairTFailedX,		AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_REP1_StartFailX', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjRepairTWonJust]=          (EventID=`TRAD_ObjRepairTWonJust,       AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_REP1_WonJust', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjRepairTWonGood]=          (EventID=`TRAD_ObjRepairTWonGood,       AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_REP1_WonGood', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjRepairTWonPerf]=          (EventID=`TRAD_ObjRepairTWonPerf,       AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_REP1_WonPerfect', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjRepairTsFailedX]=			(EventID=`TRAD_ObjRepairTsFailedX,		AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_REP9_StartFailX', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjRepairTsWonJust]=         (EventID=`TRAD_ObjRepairTsWonJust,      AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_REP9_WonJust', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjRepairTsWonGood]=         (EventID=`TRAD_ObjRepairTsWonGood,      AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_REP9_WonGood', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjRepairTsWonPerf]=         (EventID=`TRAD_ObjRepairTsWonPerf,      AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_REP9_WonPerfect', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjEscVIPFailedX]=			(EventID=`TRAD_ObjEscVIPFailedX,		AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ESC1_StartFailX', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjEscVIPWonJust]=           (EventID=`TRAD_ObjEscVIPWonJust,        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ESC1_WonJust', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjEscVIPWonGood]=           (EventID=`TRAD_ObjEscVIPWonGood,        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ESC1_WonGood', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjEscVIPWonPerf]=           (EventID=`TRAD_ObjEscVIPWonPerf,        AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ESC1_WonPerfect', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjEscVIPsFailedX]=			(EventID=`TRAD_ObjEscVIPsFailedX,		AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ESC9_StartFailX', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjEscVIPsWonJust]=          (EventID=`TRAD_ObjEscVIPsWonJust,       AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ESC9_WonJust', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjEscVIPsWonGood]=          (EventID=`TRAD_ObjEscVIPsWonGood,       AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ESC9_WonGood', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjEscVIPsWonPerf]=          (EventID=`TRAD_ObjEscVIPsWonPerf,       AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_ESC9_WonPerfect', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjCollItemFailedX]=			(EventID=`TRAD_ObjCollItemFailedX,		AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COL1_StartFailX', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjCollItemWonJust]=         (EventID=`TRAD_ObjCollItemWonJust,      AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COL1_WonJust', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjCollItemWonGood]=         (EventID=`TRAD_ObjCollItemWonGood,      AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COL1_WonGood', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjCollItemWonPerf]=         (EventID=`TRAD_ObjCollItemWonPerf,      AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COL1_WonPerfect', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjCollItemsFailedX]=		(EventID=`TRAD_ObjCollItemsFailedX,		AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COL9_StartFailX', 	Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjCollItemsWonJust]=        (EventID=`TRAD_ObjCollItemsWonJust,     AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COL9_WonJust', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjCollItemsWonGood]=        (EventID=`TRAD_ObjCollItemsWonGood,     AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COL9_WonGood', 		Priority=1, CoolDown=0.f)
	DialogEvents[`TRAD_ObjCollItemsWonPerf]=        (EventID=`TRAD_ObjCollItemsWonPerf,     AudioCue=AkEvent'WW_VOX_NPC_Trader.Play_Trader_COL9_WonPerfect', 	Priority=1, CoolDown=0.f)
}
