/*******************************************************************************
 * AICommand_Patriarch_Grab generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class AICommand_Patriarch_Grab extends AICommand_SpecialMove within KFAIController_ZedPatriarch;

static function bool TentacleGrab(KFAIController_ZedPatriarch AI)
{
    local AICommand_Patriarch_Grab Cmd;

    if(AI != none)
    {
        Cmd = new (AI) default.Class;
        if(Cmd != none)
        {
            AI.PushCommand(Cmd);
            return true;
        }
    }
    return false;
}

function Pushed()
{
    super.Pushed();
    Outer.StopAllLatentMovement();
    Outer.AIZeroMovementVariables();
    if(Outer.Enemy != none)
    {
        Outer.Focus = Outer.Enemy;
    }
    Outer.AIActionStatus = "Starting Tentacle Grab AICommand";
    if(Outer.Focus != none)
    {
        Outer.SetDesiredRotation(rotator(Outer.Focus.Location - Outer.Pawn.Location));
    }
    Outer.DisableMeleeRangeEventProbing();
}

function Popped()
{
    Outer.AIActionStatus = "Finished Tentacle Grab AICommand";
    super.Popped();
}

state Command_SpecialMove
{
    function KFGame.KFPawn.ESpecialMove GetSpecialMove()
    {
        return 3;
    }

    function bool ExecuteSpecialMove()
    {
        local KFSM_Patriarch_Grapple MyGrappleMove;

        SpecialMove = GetSpecialMove();
        Outer.AILog_Internal((string(GetFuncName()) $ "()") @ string(SpecialMove), 'Command_SpecialMove');
        if((SpecialMove != 0) && !bShouldCheckSpecialMove || Outer.MyKFPawn.CanDoSpecialMove(SpecialMove))
        {
            Outer.MyPatPawn.PlayGrabDialog();
            Outer.MyPatPawn.DoSpecialMove(SpecialMove, true, Outer.Enemy, GetSpecialMoveFlags(SpecialMove));
            MyGrappleMove = KFSM_Patriarch_Grapple(Outer.MyKFPawn.SpecialMoves[SpecialMove]);
            MyGrappleMove.TentacleDamage = Outer.MyPatPawn.TentacleDamage;
            MyGrappleMove.TentacleDmgType = Outer.MyPatPawn.TentacleDamageType;
            Outer.AIActionStatus = "SpecialMove: " $ string(Outer.MyKFPawn.SpecialMoves[SpecialMove]);
            return true;            
        }
        else
        {
            return false;
        }
    }
    stop;    
}

defaultproperties
{
    bShouldCheckSpecialMove=true
    TimeOutDelaySeconds=25
    bIgnoreNotifies=true
}