/*******************************************************************************
 * KFDT_Piercing_Crossbow generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KFDT_Piercing_Crossbow extends KFDT_Piercing
    abstract;

var float HeadStunPower;

defaultproperties
{
    HeadStunPower=1000
    WeaponDef=Class'KFGame.KFWeapDef_Crossbow'
    StunPower=30
    KnockdownPower=20
    StumblePower=250
    GunHitPower=100
    MeleeHitPower=40
    ModifierPerkList=/* Array type was not detected. */
    KDamageImpulse=1500
    KDeathVel=150
    KDeathUpKick=250
}