/*******************************************************************************
 * KFDT_Bludgeon_RifleButt generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KFDT_Bludgeon_RifleButt extends KFDT_Bludgeon
    abstract;

defaultproperties
{
    StumblePower=126
    ModifierPerkList=/* Array type was not detected. */
    bExtraMomentumZ=true
    KDamageImpulse=700
    KDeathUpKick=300
}