/*******************************************************************************
 * KFDT_Explosive_HuskCannon generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KFDT_Explosive_HuskCannon extends KFDT_Explosive
    abstract;

var class<KFDamageType> BurnDamageType;

static function ApplySecondaryDamage(KFPawn Victim, int DamageTaken, optional Controller InstigatedBy)
{
    if(default.BurnDamageType.default.DoT_Type != 0)
    {
        Victim.ApplyDamageOverTime(DamageTaken, InstigatedBy, default.BurnDamageType);
    }
}

defaultproperties
{
    BurnDamageType=Class'KFGame.KFDT_HuskCannonDot'
    WeaponDef=Class'KFGame.KFWeapDef_HuskCannon'
    bShouldSpawnPersistentBlood=true
    KnockdownPower=50
    StumblePower=170
    MeleeHitPower=50
    BurnPower=25
    ModifierPerkList=/* Array type was not detected. */
    GibImpulseScale=0.15
    bExtraMomentumZ=false
    KDamageImpulse=900
    KDeathVel=500
    KDeathUpKick=500
}