/*******************************************************************************
 * KFDT_Blast_HRG_CranialPopper generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KFDT_Blast_HRG_CranialPopper extends KFDT_Ballistic_Rifle
    abstract;

static simulated function bool CanDismemberHitZone(name InHitZoneName)
{
    switch(InHitZoneName)
    {
        case 'head':
            return false;
        default:
            return false;
            break;
    }
}

defaultproperties
{
    WeaponDef=Class'KFGame.KFWeapDef_HRG_CranialPopper'
    bCanGib=true
    GoreDamageGroup=EGoreDamageGroup.DGT_Obliteration
    StunPower=250
    StumblePower=0
    GunHitPower=0
    ModifierPerkList=/* Array type was not detected. */
    bExtraMomentumZ=true
    KDamageImpulse=0
    KDeathVel=300
    KDeathUpKick=500
    RadialDamageImpulse=1500
}