/*******************************************************************************
 * KFDT_Ballistic_Handgun generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KFDT_Ballistic_Handgun extends KFDT_Ballistic
    abstract;

defaultproperties
{
    StumblePower=4
    LegStumblePower=6
    GunHitPower=10
}