/*******************************************************************************
 * KFExplosion_SirenScream generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KFExplosion_SirenScream extends KFExplosionActor
    config(Weapon)
    hidecategories(Navigation);

protected function SpecialCringeEffectsFor(Actor Victim, float VictimDist)
{
    local KFProjectile KFProj;

    KFProj = KFProjectile(Victim);
    if((((KFProj != none) && !KFProj.bDeleteMe) && KFProj.bCanDisintegrate) && !KFProj.bHasDisintegrated)
    {
        KFProj.Disintegrate(rotator(-Velocity));
        return;
    }
}

defaultproperties
{
    bExplodeMoreThanOnce=true
}