/*******************************************************************************
 * KFGameDifficulty_Survival_Console generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KFGameDifficulty_Survival_Console extends KFGameDifficulty_Survival
    hidecategories(Object);
