/*******************************************************************************
 * KFProj_Thrown_C4 generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KFProj_Thrown_C4 extends KFProjectile
    hidecategories(Navigation);

var KFImpactEffectInfo ImpactEffectInfo;
/** "beep" sound to play (on an interval) when instigator is within blast radius */
var() AkEvent ProximityAlertAkEvent;
/** Time between proximity beeps */
var() float ProximityAlertInterval;
/** Time between proximity beeps when the instigator is within "fatal" radius */
var() float ProximityAlertIntervalClose;
var transient float ProximityAlertTimer;
var export editinline StaticMeshComponent ChargeMesh;
var MaterialInstanceConstant ChargeMIC;
var export editinline PointLightComponent BlinkLightComp;
var LinearColor BlinkColorOn;
var LinearColor BlinkColorOff;
var float BlinkTime;
var ParticleSystem BlinkFX;
var export editinline ParticleSystemComponent BlinkPSC;
var repnotify int WeaponSkinId;

replication
{
     if(bNetDirty)
        WeaponSkinId;
}

simulated function PostBeginPlay()
{
    if(WorldInfo.NetMode != NM_Client)
    {
        if(InstigatorController != none)
        {
            Class'KFGameplayPoolManager'.static.GetPoolManager().AddProjectileToPool(self, 0);            
        }
        else
        {
            Destroy();
            return;
        }
    }
    super.PostBeginPlay();
    ProximityAlertTimer = ProximityAlertInterval;
    AdjustCanDisintigrate();
    ChargeMIC = ChargeMesh.CreateAndSetMaterialInstanceConstant(0);
}

simulated event Tick(float DeltaTime)
{
    super(Actor).Tick(DeltaTime);
    StickHelper.Tick(DeltaTime);
    if(StuckToActor != none)
    {
        UpdateAlert(DeltaTime);
    }
}

simulated function UpdateAlert(float DeltaTime)
{
    local Vector ToInstigator, BBoxCenter;
    local float DistToInstigator, DamageScale;
    local Actor TraceActor;
    local Box BBox;

    if(WorldInfo.NetMode == NM_DedicatedServer)
    {
        return;
    }
    if(bHasExploded || bHasDisintegrated)
    {
        return;
    }
    if(ProximityAlertTimer <= float(0))
    {
        return;
    }
    ProximityAlertTimer -= DeltaTime;
    if(ProximityAlertTimer > float(0))
    {
        return;
    }
    ProximityAlertTimer = ProximityAlertInterval;
    if((Instigator != none) && Instigator.IsLocallyControlled())
    {
        ToInstigator = Instigator.Location - Location;
        DistToInstigator = VSize(ToInstigator);
        if(DistToInstigator <= ExplosionTemplate.DamageRadius)
        {
            Instigator.GetComponentsBoundingBox(BBox);
            BBoxCenter = (BBox.Min + BBox.Max) * 0.5;
            TraceActor = Class'GameExplosionActor'.static.StaticTraceExplosive(BBoxCenter, Location + vect(0, 0, 20), self);
            if((TraceActor == none) || TraceActor == Instigator)
            {
                DamageScale = FClamp(1 - (DistToInstigator / ExplosionTemplate.DamageRadius), 0, 1);
                DamageScale = DamageScale ** ExplosionTemplate.DamageFalloffExponent;
                if((ExplosionTemplate.Damage * DamageScale) > float(Instigator.Health))
                {
                    ProximityAlertTimer = ProximityAlertIntervalClose;
                }
                PlaySoundBase(ProximityAlertAkEvent, true);
            }
        }
    }
    BlinkOn();
}

simulated function BlinkOn()
{
    if(BlinkPSC == none)
    {
        BlinkPSC = WorldInfo.MyEmitterPool.SpawnEmitter(BlinkFX, Location + ((vect(0, 0, 4) + vect(8, 0, 0)) >> Rotation),, self,,, true);
    }
    BlinkPSC.SetFloatParameter('Glow', 1);
    ChargeMIC.SetVectorParameterValue('Vector_GlowColor', BlinkColorOn);
    BlinkLightComp.SetEnabled(true);
    SetTimer(BlinkTime, false, 'BlinkOff');
}

simulated function BlinkOff()
{
    if(BlinkPSC != none)
    {
        BlinkPSC.SetFloatParameter('Glow', 0);
    }
    ChargeMIC.SetVectorParameterValue('Vector_GlowColor', BlinkColorOff);
    BlinkLightComp.SetEnabled(false);
}

simulated function SetStickOrientation(Vector HitNormal)
{
    local Rotator StickRot;

    StickRot = CalculateStickOrientation(HitNormal);
    SetRotation(StickRot);
}

function Detonate()
{
    local KFWeap_Thrown_C4 C4WeaponOwner;
    local Vector ExplosionNormal;

    if(Role == ROLE_Authority)
    {
        C4WeaponOwner = KFWeap_Thrown_C4(Owner);
        if(C4WeaponOwner != none)
        {
            C4WeaponOwner.RemoveDeployedCharge(,, self);
        }
    }
    ExplosionNormal = vect(0, 0, 1) >> Rotation;
    Explode(Location, ExplosionNormal);
}

simulated function Explode(Vector HitLocation, Vector HitNormal)
{
    if(WorldInfo.NetMode != NM_DedicatedServer)
    {
        BlinkOff();
    }
    super.Explode(HitLocation, HitNormal);
}

simulated function Disintegrate(Rotator InDisintegrateEffectRotation)
{
    local KFWeap_Thrown_C4 C4WeaponOwner;

    if(Role == ROLE_Authority)
    {
        C4WeaponOwner = KFWeap_Thrown_C4(Owner);
        if(C4WeaponOwner != none)
        {
            C4WeaponOwner.RemoveDeployedCharge(,, self);
        }
    }
    if(WorldInfo.NetMode != NM_DedicatedServer)
    {
        BlinkOff();
    }
    super.Disintegrate(InDisintegrateEffectRotation);
}

protected simulated function PrepareExplosionTemplate()
{
    Class'KFPerk_Demolitionist'.static.PrepareExplosive(Instigator, self);
    super.PrepareExplosionTemplate();
}

protected simulated function SetExplosionActorClass()
{
    local KFPlayerReplicationInfo InstigatorPRI;

    if((WorldInfo.TimeDilation < 1) && Instigator != none)
    {
        InstigatorPRI = KFPlayerReplicationInfo(Instigator.PlayerReplicationInfo);
        if(InstigatorPRI != none)
        {
            if(InstigatorPRI.bNukeActive && Class'KFPerk_Demolitionist'.static.ProjectileShouldNuke(self))
            {
                ExplosionActorClass = Class'KFPerk_Demolitionist'.static.GetNukeExplosionActorClass();
            }
        }
    }
    super.SetExplosionActorClass();
}

function Timer_Explode()
{
    Detonate();
}

simulated event Destroyed()
{
    if(WorldInfo.NetMode != NM_Client)
    {
        if(InstigatorController != none)
        {
            Class'KFGameplayPoolManager'.static.GetPoolManager().RemoveProjectileFromPool(self, 0);
        }
    }
    super.Destroyed();
}

simulated function OnInstigatorControllerLeft()
{
    if(WorldInfo.NetMode != NM_Client)
    {
        SetTimer((1 + float(Rand(5))) + FRand(), false, 'Timer_Explode');
    }
}

simulated function SetWeaponSkin(int SkinID)
{
    local array<MaterialInterface> SkinMICs;
    local int I;

    if(SkinID > 0)
    {
        SkinMICs = Class'KFWeaponSkinList'.static.GetWeaponSkin(SkinID, 0);
        I = 0;
        J0x4E:

        if(I < SkinMICs.Length)
        {
            ChargeMesh.SetMaterial(I, SkinMICs[I]);
            ++ I;
            goto J0x4E;
        }
    }
    ChargeMIC = ChargeMesh.CreateAndSetMaterialInstanceConstant(0);
}

defaultproperties
{
    ImpactEffectInfo=KFImpactEffectInfo'WEP_C4_ARCH.C4_Projectile_Impacts'
    ProximityAlertAkEvent=AkEvent'WW_WEP_EXP_C4.Play_WEP_EXP_C4_Prox_Beep'
    ProximityAlertInterval=1
    ProximityAlertIntervalClose=0.5
    begin object name=StaticMeshComponent0 class=StaticMeshComponent
        StaticMesh=StaticMesh'WEP_3P_C4_MESH.Wep_C4_Projectile'
        ReplacementPrimitive=none
        bCastDynamicShadow=false
        CollideActors=false
        LightingChannels=(Dynamic=true)
    object end
    // Reference: StaticMeshComponent'Default__KFProj_Thrown_C4.StaticMeshComponent0'
    ChargeMesh=StaticMeshComponent0
    begin object name=BlinkPointLight class=PointLightComponent
        Radius=300
        FalloffExponent=10
        Translation=(X=8,Y=0,Z=4)
        Brightness=4
        LightColor=(B=63,G=63,R=255,A=255)
        bEnabled=false
        CastShadows=false
        CastStaticShadows=false
        CastDynamicShadows=false
        bCastPerObjectShadows=false
        LightingChannels=(Outdoor=true)
    object end
    // Reference: PointLightComponent'Default__KFProj_Thrown_C4.BlinkPointLight'
    BlinkLightComp=BlinkPointLight
    BlinkColorOn=(R=1,G=0,B=0,A=1)
    BlinkColorOff=(R=0,G=0,B=0,A=1)
    BlinkTime=0.2
    BlinkFX=ParticleSystem'WEP_C4_EMIT.FX_C4_Glow'
    bAlwaysReplicateExplosion=true
    bCanDisintegrate=true
    bCanStick=true
    AlwaysRelevantDistanceSquared=6250000
    GlassShatterType=FracturedMeshGlassShatterType.FMGS_ShatterDamaged
    TossZ=100
    ExplosionActorClass=Class'KFExplosionActorC4'
    begin object name=ExploTemplate0 class=KFGameExplosion
        ExplosionEffects=KFImpactEffectInfo'WEP_C4_ARCH.C4_Explosion'
        Damage=820
        DamageRadius=400
        DamageFalloffExponent=2
        MyDamageType=Class'KFDT_Explosive_C4'
        KnockDownStrength=0
        ExplosionSound=AkEvent'WW_WEP_EXP_C4.Play_WEP_EXP_C4_Explosion'
        ExploLight=PointLightComponent'Default__KFProj_Thrown_C4.ExplosionPointLight'
        ExploLightFadeOutTime=0.2
        CamShake=KFCameraShake'FX_CameraShake_Arch.Misc_Explosions.Light_Explosion_Rumble'
        CamShakeInnerRadius=200
        CamShakeFalloff=1.5
    object end
    // Reference: KFGameExplosion'Default__KFProj_Thrown_C4.ExploTemplate0'
    ExplosionTemplate=ExploTemplate0
    ProjDisintegrateTemplate=ParticleSystem'ZED_Siren_EMIT.FX_Siren_grenade_disable_01'
    AltExploEffects=KFImpactEffectInfo'WEP_C4_ARCH.C4_Explosion_Concussive_Force'
    StuckToBoneIdx=-1
    begin object name=StickHelper0 class=KFProjectileStickHelper
        StickAkEvent=AkEvent'WW_WEP_EXP_C4.Play_WEP_EXP_C4_Handling_Place'
    object end
    // Reference: KFProjectileStickHelper'Default__KFProj_Thrown_C4.StickHelper0'
    StickHelper=StickHelper0
    Speed=1200
    MaxSpeed=1200
    bBlockedByInstigator=false
    bIgnoreFoliageTouch=true
    DamageRadius=0
    begin object name=CollisionCylinder class=CylinderComponent
        ReplacementPrimitive=none
        CollideActors=true
        BlockNonZeroExtent=false
    object end
    // Reference: CylinderComponent'Default__KFProj_Thrown_C4.CollisionCylinder'
    CylinderComponent=CollisionCylinder
    begin object name=CollisionCylinder class=CylinderComponent
        ReplacementPrimitive=none
        CollideActors=true
        BlockNonZeroExtent=false
    object end
    // Reference: CylinderComponent'Default__KFProj_Thrown_C4.CollisionCylinder'
    Components(0)=CollisionCylinder
    begin object name=BlinkPointLight class=PointLightComponent
        Radius=300
        FalloffExponent=10
        Translation=(X=8,Y=0,Z=4)
        Brightness=4
        LightColor=(B=63,G=63,R=255,A=255)
        bEnabled=false
        CastShadows=false
        CastStaticShadows=false
        CastDynamicShadows=false
        bCastPerObjectShadows=false
        LightingChannels=(Outdoor=true)
    object end
    // Reference: PointLightComponent'Default__KFProj_Thrown_C4.BlinkPointLight'
    Components(1)=BlinkPointLight
    begin object name=StaticMeshComponent0 class=StaticMeshComponent
        StaticMesh=StaticMesh'WEP_3P_C4_MESH.Wep_C4_Projectile'
        ReplacementPrimitive=none
        bCastDynamicShadow=false
        CollideActors=false
        LightingChannels=(Dynamic=true)
    object end
    // Reference: StaticMeshComponent'Default__KFProj_Thrown_C4.StaticMeshComponent0'
    Components(2)=StaticMeshComponent0
    Physics=EPhysics.PHYS_Falling
    bNetTemporary=false
    bCollideComplex=true
    bBounce=true
    LifeSpan=0
    begin object name=CollisionCylinder class=CylinderComponent
        ReplacementPrimitive=none
        CollideActors=true
        BlockNonZeroExtent=false
    object end
    // Reference: CylinderComponent'Default__KFProj_Thrown_C4.CollisionCylinder'
    CollisionComponent=CollisionCylinder
}