/*******************************************************************************
 * KFProj_FlareGunSplash generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KFProj_FlareGunSplash extends KFProj_MolotovSplash
    hidecategories(Navigation);

defaultproperties
{
    begin object name=ExploTemplate0 class=KFGameExplosion
        MyDamageType=Class'KFDT_Fire_Ground_FlareGun'
        ExploLight=PointLightComponent'Default__KFProj_FlareGunSplash.FlamePointLight'
    object end
    // Reference: KFGameExplosion'Default__KFProj_FlareGunSplash.ExploTemplate0'
    ExplosionTemplate=ExploTemplate0
    AmbientComponent=AkComponent'Default__KFProj_FlareGunSplash.AmbientAkSoundComponent'
    AssociatedPerkClass=none
    begin object name=CollisionCylinder class=CylinderComponent
        ReplacementPrimitive=none
    object end
    // Reference: CylinderComponent'Default__KFProj_FlareGunSplash.CollisionCylinder'
    CylinderComponent=CollisionCylinder
    begin object name=CollisionCylinder class=CylinderComponent
        ReplacementPrimitive=none
    object end
    // Reference: CylinderComponent'Default__KFProj_FlareGunSplash.CollisionCylinder'
    Components(0)=CollisionCylinder
    Components(1)=AkComponent'Default__KFProj_FlareGunSplash.AmbientAkSoundComponent'
    begin object name=CollisionCylinder class=CylinderComponent
        ReplacementPrimitive=none
    object end
    // Reference: CylinderComponent'Default__KFProj_FlareGunSplash.CollisionCylinder'
    CollisionComponent=CollisionCylinder
}