/*******************************************************************************
 * KFProj_MolotovFlare generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KFProj_MolotovFlare extends Actor
    notplaceable
    hidecategories(Navigation);

var export editinline ParticleSystemComponent ProjEffects;
var(Projectile) ParticleSystem ProjFlightTemplate;
var export editinline PointLightComponent PointLight;
var float LightFadeStartTime;
var float LightFadeTime;
var transient float LightFadePerSecond;
var AkEvent FuseEvent;

simulated event PostBeginPlay()
{
    super.PostBeginPlay();
    if(ProjFlightTemplate != none)
    {
        ProjEffects = WorldInfo.MyEmitterPool.SpawnEmitterCustomLifetime(ProjFlightTemplate);
        if(ProjEffects != none)
        {
            ProjEffects.SetAbsolute(false, false, false);
            ProjEffects.SetLODLevel(((WorldInfo.bDropDetail) ? 1 : 0));
            ProjEffects.bUpdateComponentInTick = true;
            ProjEffects.SetTranslation(vect(0, 0, 2));
            AttachComponent(ProjEffects);
        }
    }
    LightFadePerSecond = PointLight.Brightness / LightFadeTime;
    PlaySoundBase(FuseEvent, true,, true);
}

simulated event Tick(float DeltaTime)
{
    local float NewBrightness;

    super.Tick(DeltaTime);
    if(LifeSpan < (default.LifeSpan - LightFadeStartTime))
    {
        if(PointLight.Brightness > float(0))
        {
            NewBrightness = FMax(0, PointLight.Brightness - (LightFadePerSecond * DeltaTime));
            PointLight.SetLightProperties(NewBrightness);
        }
    }
}

defaultproperties
{
    ProjFlightTemplate=ParticleSystem'WEP_3P_Molotov_EMIT.FX_Flare_fire_01'
    begin object name=PointLightComponent0 class=PointLightComponent
        Radius=800
        FalloffExponent=10
        Brightness=3
        LightColor=(B=140,G=190,R=245,A=255)
        CastShadows=false
        CastStaticShadows=false
        CastDynamicShadows=false
        LightingChannels=(Outdoor=true)
    object end
    // Reference: PointLightComponent'Default__KFProj_MolotovFlare.PointLightComponent0'
    PointLight=PointLightComponent0
    LightFadeStartTime=27.5
    LightFadeTime=2.75
    FuseEvent=AkEvent'WW_WEP_EXP_Dynamite.Play_WEP_EXP_Dynamite_Fuse_LP'
    begin object name=CollisionCylinder class=CylinderComponent
        CollisionHeight=0
        CollisionRadius=0
        ReplacementPrimitive=none
    object end
    // Reference: CylinderComponent'Default__KFProj_MolotovFlare.CollisionCylinder'
    Components(0)=CollisionCylinder
    begin object name=PointLightComponent0 class=PointLightComponent
        Radius=800
        FalloffExponent=10
        Brightness=3
        LightColor=(B=140,G=190,R=245,A=255)
        CastShadows=false
        CastStaticShadows=false
        CastDynamicShadows=false
        LightingChannels=(Outdoor=true)
    object end
    // Reference: PointLightComponent'Default__KFProj_MolotovFlare.PointLightComponent0'
    Components(1)=PointLightComponent0
    Physics=EPhysics.PHYS_Falling
    RemoteRole=ENetRole.ROLE_SimulatedProxy
    bNetTemporary=true
    bAlwaysRelevant=true
    bReplicateInstigator=true
    bSkipActorPropertyReplication=true
    bCollideActors=true
    bCollideWorld=true
    bCollideComplex=true
    NetPriority=2.5
    LifeSpan=31
    begin object name=CollisionCylinder class=CylinderComponent
        CollisionHeight=0
        CollisionRadius=0
        ReplacementPrimitive=none
    object end
    // Reference: CylinderComponent'Default__KFProj_MolotovFlare.CollisionCylinder'
    CollisionComponent=CollisionCylinder
}