/*******************************************************************************
 * KFWeap_Blunt_Pulverizer generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KFWeap_Blunt_Pulverizer extends KFWeap_MeleeBase
    config(Game)
    hidecategories(Navigation,Advanced,Collision,Mobile,Movement,Object,Physics,Attachment,Debug);

const ShootAnim_L = 'HardFire_L';
const ShootAnim_R = 'HardFire_R';
const ShootAnim_F = 'HardFire_F';
const ShootAnim_B = 'HardFire_B';

var bool bWasTimeDilated;
var bool bAltExploEffects;
var transient bool bPulverizerFireReleased;
var bool bFriendlyFireEnabled;
var class<KFExplosionActor> ExplosionActorClass;
var() KFGameExplosion ExplosionTemplate;
var KFImpactEffectInfo AltExploEffects;
var transient Actor BlastAttachee;
var transient float BlastSpawnOffset;
var class<KFExplosionActor> NukeExplosionActorClass;
var float StartingDamageRadius;

replication
{
     if(bNetInitial)
        bFriendlyFireEnabled;
}

simulated event PreBeginPlay()
{
    super(KFWeapon).PreBeginPlay();
    if((Role == ROLE_Authority) && KFGameInfo(WorldInfo.Game).FriendlyFireScale != 0)
    {
        bFriendlyFireEnabled = true;
    }
    if(ExplosionTemplate != none)
    {
        StartingDamageRadius = ExplosionTemplate.DamageRadius;
    }
}

simulated function bool HasAnyAmmo()
{
    if((HasSpareAmmo()) || AmmoCount[0] >= AmmoCost[6])
    {
        return true;
    }
    return false;
}

simulated event bool HasAmmo(byte FireModeNum, optional int Amount)
{
    if(FireModeNum == 0)
    {
        return true;
    }
    return super(KFWeapon).HasAmmo(FireModeNum, Amount);
}

simulated function bool CanOverrideMagReload(byte FireModeNum)
{
    return FireModeNum != 2;
}

simulated function CustomFire()
{
    local KFExplosionActor ExploActor;
    local Vector SpawnLoc;
    local Rotator SpawnRot;

    if(Instigator.Role < ROLE_Authority)
    {
        return;
    }
    if(((WorldInfo.NetMode == NM_ListenServer) || WorldInfo.NetMode == NM_DedicatedServer) || Instigator.Controller != none)
    {
        bWasTimeDilated = WorldInfo.TimeDilation < 1;
    }
    PrepareExplosionTemplate();
    SetExplosionActorClass();
    SpawnLoc = Instigator.GetWeaponStartTraceLocation();
    SpawnRot = GetPulverizerAim(SpawnLoc);
    SpawnLoc += (vector(SpawnRot) * BlastSpawnOffset);
    ExploActor = Spawn(ExplosionActorClass, self,, SpawnLoc, SpawnRot,, true);
    if(ExploActor != none)
    {
        ExploActor.InstigatorController = Instigator.Controller;
        ExploActor.Instigator = Instigator;
        ExploActor.Attachee = BlastAttachee;
        ExplosionTemplate.bFullDamageToAttachee = true;
        ExploActor.bReplicateInstigator = true;
        ExploActor.SetSyncToMuzzleLocation(true);
        ExploActor.Explode(ExplosionTemplate, vector(SpawnRot));
    }
    IncrementFlashCount();
    if(bDebug)
    {
        DrawDebugCone(SpawnLoc, vector(SpawnRot), ExplosionTemplate.DamageRadius, ExplosionTemplate.DirectionalExplosionAngleDeg * 0.01745329, ExplosionTemplate.DirectionalExplosionAngleDeg * 0.01745329, 16, MakeColor(64, 64, 255, 0), true);
    }
}

protected simulated function PrepareExplosionTemplate()
{
    local KFPlayerReplicationInfo InstigatorPRI;
    local KFPlayerController KFPC;
    local KFPerk InstigatorPerk;

    if(bWasTimeDilated)
    {
        InstigatorPRI = KFPlayerReplicationInfo(Instigator.PlayerReplicationInfo);
        if(InstigatorPRI != none)
        {
            if(InstigatorPRI.bNukeActive)
            {
                ExplosionTemplate = Class'KFPerk_Demolitionist'.static.GetNukeExplosionTemplate();
                ExplosionTemplate.Damage = ExplosionTemplate.Damage * Class'KFPerk_Demolitionist'.static.GetNukeDamageModifier();
                ExplosionTemplate.DamageRadius = ExplosionTemplate.DamageRadius * Class'KFPerk_Demolitionist'.static.GetNukeRadiusModifier();
                ExplosionTemplate.DamageFalloffExponent = ExplosionTemplate.DamageFalloffExponent;                
            }
            else
            {
                if(InstigatorPRI.bConcussiveActive && AltExploEffects != none)
                {
                    ExplosionTemplate.ExplosionEffects = AltExploEffects;
                    ExplosionTemplate.ExplosionSound = Class'KFPerk_Demolitionist'.static.GetConcussiveExplosionSound();
                }
            }
        }        
    }
    else
    {
        ExplosionTemplate = default.ExplosionTemplate;
        ExplosionTemplate.DamageRadius = StartingDamageRadius;
    }
    if(Owner.Role == ROLE_Authority)
    {
        KFPC = KFPlayerController(Instigator.Controller);
        if(KFPC != none)
        {
            InstigatorPerk = KFPC.GetPerk();
            ExplosionTemplate.DamageRadius *= InstigatorPerk.GetAoERadiusModifier();
        }
    }
}

protected simulated function SetExplosionActorClass()
{
    local KFPlayerReplicationInfo InstigatorPRI;

    if(bWasTimeDilated && Instigator != none)
    {
        InstigatorPRI = KFPlayerReplicationInfo(Instigator.PlayerReplicationInfo);
        if(InstigatorPRI != none)
        {
            if(InstigatorPRI.bNukeActive)
            {
                ExplosionActorClass = NukeExplosionActorClass;
                return;
            }
        }
    }
    ExplosionActorClass = default.ExplosionActorClass;
}

simulated function Rotator GetPulverizerAim(Vector StartFireLoc)
{
    local Rotator R;

    R = GetAdjustedAim(StartFireLoc);
    switch(MeleeAttackHelper.CurrentAttackDir)
    {
        case 2:
            R.Yaw += 5461;
            break;
        case 3:
            R.Yaw -= 5461;
            break;
        case 0:
            R.Pitch -= 2048;
            break;
        case 1:
            R.Pitch += 2048;
            break;
        default:
            break;
    }
    return R;
}

simulated function name GetWeaponFireAnim(byte FireModeNum)
{
    switch(MeleeAttackHelper.CurrentAttackDir)
    {
        case 0:
        case 4:
        case 5:
            return 'HardFire_F';
        case 1:
        case 6:
        case 7:
            return 'HardFire_B';
        case 2:
            return 'HardFire_L';
        case 3:
            return 'HardFire_R';
        default:
            return 'None';
            break;
    }
}

private reliable server final function ServerBeginPulverizerFire(Actor HitActor, optional Vector HitLocation)
{
    if(VSizeSq2D(HitLocation - Instigator.Location) > Square(500))
    {
        LogInternal("ServerBeginPulverizerFire outside of range!");
        return;
    }
    BlastAttachee = HitActor;
    SendToFiringState(6);
}

simulated function BeginPulverizerFire()
{
    SendToFiringState(6);
}

simulated function bool ShouldRefire()
{
    if(CurrentFireMode == 6)
    {
        return false;
    }
    return super(Weapon).ShouldRefire();
}

simulated function SendToFiringState(byte FireModeNum)
{
    if((FireModeNum == 2) && !CanReload())
    {
        SetCurrentFireMode(FireModeNum);
        GotoState('WeaponUpkeep');
        return;
    }
    super.SendToFiringState(FireModeNum);
}

simulated function bool CanReload(optional byte FireModeNum)
{
    return true;
}

simulated state MeleeHeavyAttacking
{
    simulated event BeginState(name PreviousStateName)
    {
        super.BeginState(PreviousStateName);
        bPulverizerFireReleased = false;
    }

    simulated function StopFire(byte FireModeNum)
    {
        super(KFWeapon).StopFire(FireModeNum);
        bPulverizerFireReleased = true;
    }

    simulated function NotifyMeleeCollision(Actor HitActor, optional Vector HitLocation)
    {
        local KFPawn Victim;

        if((Instigator != none) && Instigator.IsLocallyControlled())
        {
            if(HitActor.bWorldGeometry)
            {
                return;
            }
            Victim = KFPawn(HitActor);
            if(((Victim == none) || !bFriendlyFireEnabled && Victim.GetTeamNum() == Instigator.GetTeamNum()) || Victim.bPlayedDeath && (WorldInfo.TimeSeconds - Victim.TimeOfDeath) > 0)
            {
                return;
            }
            if((AmmoCount[0] >= AmmoCost[6]) && !IsTimerActive('BeginPulverizerFire'))
            {
                BlastAttachee = HitActor;
                SetTimer(0.001, false, 'BeginPulverizerFire');
                if(Role < ROLE_Authority)
                {
                    if(HitActor.bTearOff && Victim != none)
                    {
                        Victim.TakeRadiusDamage(Instigator.Controller, ExplosionTemplate.Damage, ExplosionTemplate.DamageRadius, ExplosionTemplate.MyDamageType, ExplosionTemplate.MomentumTransferScale, Location, true, ((Owner != none) ? Owner : self));                        
                    }
                    else
                    {
                        ServerBeginPulverizerFire(HitActor, HitLocation);
                    }
                }
            }
        }
    }
    stop;    
}

simulated state Active
{
    simulated function WeaponEmpty()
    {
        local int I;

        I = 0;
        J0x0B:

        if(I < GetPendingFireLength())
        {
            if(PendingFire(I))
            {
                BeginFire(byte(I));
                goto J0x5F;
            }
            ++ I;
            goto J0x0B;
        }
        J0x5F:

    }
    stop;    
}

defaultproperties
{
    ExplosionActorClass=Class'KFGame.KFExplosionActorReplicated'
    ExplosionTemplate=KFGameExplosion'WEP_Pulverizer_ARCH.Wep_Pulverizer_Explosion'
    AltExploEffects=KFImpactEffectInfo'WEP_RPG7_ARCH.RPG7_Explosion_Concussive_Force'
    BlastSpawnOffset=-10
    NukeExplosionActorClass=Class'KFGame.KFExplosion_ReplicatedNuke'
    ParryStrength=5
    ParryDamageMitigationPercent=0.4
    BlockSound=AkEvent'WW_WEP_Bullet_Impacts.Play_Block_MEL_Hammer'
    ParrySound=AkEvent'WW_WEP_Bullet_Impacts.Play_Parry_Wood'
    PackageKey="Pulverizer"
    FirstPersonMeshName="WEP_1P_Pulverizer_MESH.Wep_1stP_Pulverizer_Rig_New"
    FirstPersonAnimSetNames=/* Array type was not detected. */
    PickupMeshName="WEP_3P_Pulverizer_MESH.Wep_Pulverizer_Pickup"
    AttachmentArchetypeName="WEP_Pulverizer_ARCH.Wep_Pulverizer_3P"
    MuzzleFlashTemplateName="WEP_Pulverizer_ARCH.Wep_Pulverizer_MuzzleFlash"
    bCanBeReloaded=true
    bReloadFromMagazine=true
    FireModeIconPaths=/* Array type was not detected. */
    InventorySize=6
    GroupPriority=75
    WeaponSelectTexture=Texture2D'ui_weaponselect_tex.UI_WeaponSelect_Pulverizer'
    MagazineCapacity=5
    AmmoCost=/* Array type was not detected. */
    SpareAmmoCapacity=15
    WeaponFireSnd=/* Array type was not detected. */
    begin object name=MeleeHelper class=KFMeleeHelperWeapon
        ChainSequence_F=/* Array type was not detected. */
        ChainSequence_B=/* Array type was not detected. */
        ChainSequence_L=/* Array type was not detected. */
        ChainSequence_R=/* Array type was not detected. */
        MeleeImpactCamShakeScale=0.04
        MaxHitRange=190
        HitboxChain=/* Array type was not detected. */
    object end
    // Reference: KFMeleeHelperWeapon'Default__KFWeap_Blunt_Pulverizer.MeleeHelper'
    MeleeAttackHelper=MeleeHelper
    AssociatedPerkClasses=/* Array type was not detected. */
    WeaponUpgrades=/* Array type was not detected. */
    FiringStatesArray=/* Array type was not detected. */
    WeaponFireTypes=/* Array type was not detected. */
    FireInterval=/* Array type was not detected. */
    InstantHitDamage=/* Array type was not detected. */
    InstantHitDamageTypes=/* Array type was not detected. */
    begin object name=FirstPersonMesh class=KFSkeletalMeshComponent
        ReplacementPrimitive=none
    object end
    // Reference: KFSkeletalMeshComponent'Default__KFWeap_Blunt_Pulverizer.FirstPersonMesh'
    Mesh=FirstPersonMesh
    ItemName="Pulverizer"
    begin object name=StaticPickupComponent class=StaticMeshComponent
        ReplacementPrimitive=none
    object end
    // Reference: StaticMeshComponent'Default__KFWeap_Blunt_Pulverizer.StaticPickupComponent'
    DroppedPickupMesh=StaticPickupComponent
    begin object name=StaticPickupComponent class=StaticMeshComponent
        ReplacementPrimitive=none
    object end
    // Reference: StaticMeshComponent'Default__KFWeap_Blunt_Pulverizer.StaticPickupComponent'
    PickupFactoryMesh=StaticPickupComponent
}