//=============================================================================
// KFWeaponSkinList
//=============================================================================
//
//=============================================================================
// Killing Floor 2
// Copyright (C) 2015 Tripwire Interactive LLC
//=============================================================================

class KFWeaponSkinList extends Object
	abstract
    native;

struct native WeaponSkin
{
	/** Steam item Id */
	var int 	Id;

	/** Material DLO Paths */
	var array<string> 	MIC_1P;
	var string 			MIC_3P;
	var string  		MIC_Pickup;

	/** Basic Info about associated weapon */
	var class<KFWeaponDefinition> WeaponDef;
};

enum EWeaponSkinType
{
	WST_FirstPerson,
	WST_ThirdPerson,
	WST_Pickup,
};

var const array<WeaponSkin> Skins;

/** Returns material given a weapon skin item Id */
static native function array<MaterialInterface> GetWeaponSkin(int ItemId, EWeaponSkinType Type);

/** Inventory UI, read / write skin equip */
static native function SaveWeaponSkin(class<KFWeaponDefinition> WeaponDef, int ID);
static native function bool IsSkinEquip(class<KFWeaponDefinition> WeaponDef, int ID);

defaultproperties
{
   Skins(0)=(Id=3001,MIC_1P=("WEP_SkinSet01_MAT.anodizedhazard_ar15.AnodizedHazard_AR15_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.anodizedhazard_ar15.AnodizedHazard_AR15_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.anodizedhazard_ar15.AnodizedHazard_AR15_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AR15')
   Skins(1)=(Id=3002,MIC_1P=("WEP_SkinSet01_MAT.anodizedhazard_ar15.AnodizedHazard_AR15_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.anodizedhazard_ar15.AnodizedHazard_AR15_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.anodizedhazard_ar15.AnodizedHazard_AR15_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AR15')
   Skins(2)=(Id=3003,MIC_1P=("WEP_SkinSet01_MAT.anodizedhazard_ar15.AnodizedHazard_AR15_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.anodizedhazard_ar15.AnodizedHazard_AR15_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.anodizedhazard_ar15.AnodizedHazard_AR15_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AR15')
   Skins(3)=(Id=3004,MIC_1P=("WEP_SkinSet01_MAT.airlock_9mm.Airlock_9MM_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.airlock_9mm.Airlock_9MM_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.airlock_9mm.Airlock_9MM_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_9mm')
   Skins(4)=(Id=3005,MIC_1P=("WEP_SkinSet01_MAT.airlock_9mm.Airlock_9MM_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.airlock_9mm.Airlock_9MM_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.airlock_9mm.Airlock_9MM_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_9mm')
   Skins(5)=(Id=3006,MIC_1P=("WEP_SkinSet01_MAT.airlock_9mm.Airlock_9MM_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.airlock_9mm.Airlock_9MM_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.airlock_9mm.Airlock_9MM_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_9mm')
   Skins(6)=(Id=3007,MIC_1P=("WEP_SkinSet01_MAT.aeronaut_bullpup.Aeronaut_Bullpup_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.aeronaut_bullpup.Aeronaut_Bullpup_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.aeronaut_bullpup.Aeronaut_Bullpup_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Bullpup')
   Skins(7)=(Id=3008,MIC_1P=("WEP_SkinSet01_MAT.aeronaut_bullpup.Aeronaut_Bullpup_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.aeronaut_bullpup.Aeronaut_Bullpup_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.aeronaut_bullpup.Aeronaut_Bullpup_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Bullpup')
   Skins(8)=(Id=3009,MIC_1P=("WEP_SkinSet01_MAT.aeronaut_bullpup.Aeronaut_Bullpup_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.aeronaut_bullpup.Aeronaut_Bullpup_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.aeronaut_bullpup.Aeronaut_Bullpup_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Bullpup')
   Skins(9)=(Id=3010,MIC_1P=("WEP_SkinSet01_MAT.woodland_aa12.Woodland_AA12_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.woodland_aa12.Woodland_AA12_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.woodland_aa12.Woodland_AA12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AA12')
   Skins(10)=(Id=3011,MIC_1P=("WEP_SkinSet01_MAT.woodland_aa12.Woodland_AA12_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.woodland_aa12.Woodland_AA12_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.woodland_aa12.Woodland_AA12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AA12')
   Skins(11)=(Id=3012,MIC_1P=("WEP_SkinSet01_MAT.woodland_aa12.Woodland_AA12_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.woodland_aa12.Woodland_AA12_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.woodland_aa12.Woodland_AA12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AA12')
   Skins(12)=(Id=3013,MIC_1P=("WEP_SkinSet01_MAT.woodland_doublebarrel.Woodland_DoubleBarrel_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.woodland_doublebarrel.Woodland_DoubleBarrel_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.woodland_doublebarrel.Woodland_DoubleBarrel_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_DoubleBarrel')
   Skins(13)=(Id=3014,MIC_1P=("WEP_SkinSet01_MAT.woodland_doublebarrel.Woodland_DoubleBarrel_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.woodland_doublebarrel.Woodland_DoubleBarrel_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.woodland_doublebarrel.Woodland_DoubleBarrel_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_DoubleBarrel')
   Skins(14)=(Id=3015,MIC_1P=("WEP_SkinSet01_MAT.woodland_doublebarrel.Woodland_DoubleBarrel_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.woodland_doublebarrel.Woodland_DoubleBarrel_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.woodland_doublebarrel.Woodland_DoubleBarrel_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_DoubleBarrel')
   Skins(15)=(Id=3016,MIC_1P=("WEP_SkinSet01_MAT.woodland_bullpup.Woodland_Bullpup_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.woodland_bullpup.Woodland_Bullpup_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.woodland_bullpup.Woodland_Bullpup_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Bullpup')
   Skins(16)=(Id=3017,MIC_1P=("WEP_SkinSet01_MAT.woodland_bullpup.Woodland_Bullpup_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.woodland_bullpup.Woodland_Bullpup_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.woodland_bullpup.Woodland_Bullpup_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Bullpup')
   Skins(17)=(Id=3018,MIC_1P=("WEP_SkinSet01_MAT.woodland_bullpup.Woodland_Bullpup_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.woodland_bullpup.Woodland_Bullpup_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.woodland_bullpup.Woodland_Bullpup_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Bullpup')
   Skins(18)=(Id=3019,MIC_1P=("WEP_SkinSet01_MAT.woodland_scar.Woodland_SCAR_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.woodland_scar.Woodland_SCAR_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.woodland_scar.Woodland_SCAR_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_SCAR')
   Skins(19)=(Id=3020,MIC_1P=("WEP_SkinSet01_MAT.woodland_scar.Woodland_SCAR_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.woodland_scar.Woodland_SCAR_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.woodland_scar.Woodland_SCAR_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_SCAR')
   Skins(20)=(Id=3021,MIC_1P=("WEP_SkinSet01_MAT.woodland_scar.Woodland_SCAR_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.woodland_scar.Woodland_SCAR_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.woodland_scar.Woodland_SCAR_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_SCAR')
   Skins(21)=(Id=3022,MIC_1P=("WEP_SkinSet01_MAT.arachnid_nailgun.Arachnid_NailGun_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.arachnid_nailgun.Arachnid_NailGun_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.arachnid_nailgun.Arachnid_NailGun_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Nailgun')
   Skins(22)=(Id=3023,MIC_1P=("WEP_SkinSet01_MAT.arachnid_nailgun.Arachnid_NailGun_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.arachnid_nailgun.Arachnid_NailGun_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.arachnid_nailgun.Arachnid_NailGun_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Nailgun')
   Skins(23)=(Id=3024,MIC_1P=("WEP_SkinSet01_MAT.arachnid_nailgun.Arachnid_NailGun_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.arachnid_nailgun.Arachnid_NailGun_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.arachnid_nailgun.Arachnid_NailGun_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Nailgun')
   Skins(24)=(Id=3025,MIC_1P=("WEP_SkinSet01_MAT.bloated_9mm.Bloated_9mm_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.bloated_9mm.Bloated_9mm_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.bloated_9mm.Bloated_9mm_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_9mm')
   Skins(25)=(Id=3026,MIC_1P=("WEP_SkinSet01_MAT.bloated_9mm.Bloated_9mm_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.bloated_9mm.Bloated_9mm_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.bloated_9mm.Bloated_9mm_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_9mm')
   Skins(26)=(Id=3027,MIC_1P=("WEP_SkinSet01_MAT.bloated_9mm.Bloated_9mm_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.bloated_9mm.Bloated_9mm_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.bloated_9mm.Bloated_9mm_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_9mm')
   Skins(27)=(Id=3028,MIC_1P=("WEP_SkinSet01_MAT.monsterkiller_m4.MonsterKiller_M4_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.monsterkiller_m4.MonsterKiller_M4_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.monsterkiller_m4.MonsterKiller_M4_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_M4')
   Skins(28)=(Id=3029,MIC_1P=("WEP_SkinSet01_MAT.monsterkiller_m4.MonsterKiller_M4_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.monsterkiller_m4.MonsterKiller_M4_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.monsterkiller_m4.MonsterKiller_M4_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_M4')
   Skins(29)=(Id=3030,MIC_1P=("WEP_SkinSet01_MAT.monsterkiller_m4.MonsterKiller_M4_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.monsterkiller_m4.MonsterKiller_M4_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.monsterkiller_m4.MonsterKiller_M4_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_M4')
   Skins(30)=(Id=3031,MIC_1P=("WEP_SkinSet01_MAT.gravedigger_crovel.GraveDigger_Crovel_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.gravedigger_crovel.GraveDigger_Crovel_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.gravedigger_crovel.GraveDigger_Crovel_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Crovel')
   Skins(31)=(Id=3032,MIC_1P=("WEP_SkinSet01_MAT.gravedigger_crovel.GraveDigger_Crovel_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.gravedigger_crovel.GraveDigger_Crovel_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.gravedigger_crovel.GraveDigger_Crovel_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Crovel')
   Skins(32)=(Id=3033,MIC_1P=("WEP_SkinSet01_MAT.gravedigger_crovel.GraveDigger_Crovel_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.gravedigger_crovel.GraveDigger_Crovel_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.gravedigger_crovel.GraveDigger_Crovel_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Crovel')
   Skins(33)=(Id=3036,MIC_1P=("WEP_SkinSet01_MAT.clotcommando_scar.ClotCommando_SCAR_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.clotcommando_scar.ClotCommando_SCAR_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.clotcommando_scar.ClotCommando_SCAR_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_SCAR')
   Skins(34)=(Id=3035,MIC_1P=("WEP_SkinSet01_MAT.clotcommando_scar.ClotCommando_SCAR_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.clotcommando_scar.ClotCommando_SCAR_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.clotcommando_scar.ClotCommando_SCAR_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_SCAR')
   Skins(35)=(Id=3034,MIC_1P=("WEP_SkinSet01_MAT.clotcommando_scar.ClotCommando_SCAR_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.clotcommando_scar.ClotCommando_SCAR_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.clotcommando_scar.ClotCommando_SCAR_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_SCAR')
   Skins(36)=(Id=3039,MIC_1P=("WEP_SkinSet01_MAT.sharkteeth_doublebarrel.SharkTeeth_DoubleBarrel_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.sharkteeth_doublebarrel.SharkTeeth_DoubleBarrel_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.sharkteeth_doublebarrel.SharkTeeth_DoubleBarrel_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_DoubleBarrel')
   Skins(37)=(Id=3038,MIC_1P=("WEP_SkinSet01_MAT.sharkteeth_doublebarrel.SharkTeeth_DoubleBarrel_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.sharkteeth_doublebarrel.SharkTeeth_DoubleBarrel_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.sharkteeth_doublebarrel.SharkTeeth_DoubleBarrel_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_DoubleBarrel')
   Skins(38)=(Id=3037,MIC_1P=("WEP_SkinSet01_MAT.sharkteeth_doublebarrel.SharkTeeth_DoubleBarrel_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.sharkteeth_doublebarrel.SharkTeeth_DoubleBarrel_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.sharkteeth_doublebarrel.SharkTeeth_DoubleBarrel_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_DoubleBarrel')
   Skins(39)=(Id=3040,MIC_1P=("WEP_SkinSet01_MAT.tiger_rpg7.Tiger_RPG7_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.tiger_rpg7.Tiger_RPG7_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.tiger_rpg7.Tiger_RPG7_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_RPG7')
   Skins(40)=(Id=3041,MIC_1P=("WEP_SkinSet01_MAT.tiger_rpg7.Tiger_RPG7_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.tiger_rpg7.Tiger_RPG7_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.tiger_rpg7.Tiger_RPG7_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_RPG7')
   Skins(41)=(Id=3042,MIC_1P=("WEP_SkinSet01_MAT.tiger_rpg7.Tiger_RPG7_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.tiger_rpg7.Tiger_RPG7_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.tiger_rpg7.Tiger_RPG7_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_RPG7')
   Skins(42)=(Id=3046,MIC_1P=("WEP_SkinSet01_MAT.tiger_m79.Tiger_M79_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.tiger_m79.Tiger_M79_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.tiger_m79.Tiger_M79_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_M79')
   Skins(43)=(Id=3045,MIC_1P=("WEP_SkinSet01_MAT.tiger_m79.Tiger_M79_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.tiger_m79.Tiger_M79_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.tiger_m79.Tiger_M79_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_M79')
   Skins(44)=(Id=3044,MIC_1P=("WEP_SkinSet01_MAT.tiger_m79.Tiger_M79_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.tiger_m79.Tiger_M79_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.tiger_m79.Tiger_M79_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_M79')
   Skins(45)=(Id=3049,MIC_1P=("WEP_SkinSet01_MAT.tiger_hx25.Tiger_HX25_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.tiger_hx25.Tiger_HX25_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.tiger_hx25.Tiger_HX25_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_HX25')
   Skins(46)=(Id=3048,MIC_1P=("WEP_SkinSet01_MAT.tiger_hx25.Tiger_HX25_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.tiger_hx25.Tiger_HX25_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.tiger_hx25.Tiger_HX25_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_HX25')
   Skins(47)=(Id=3047,MIC_1P=("WEP_SkinSet01_MAT.tiger_hx25.Tiger_HX25_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.tiger_hx25.Tiger_HX25_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.tiger_hx25.Tiger_HX25_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_HX25')
   Skins(48)=(Id=3052,MIC_1P=("WEP_SkinSet01_MAT.tiger_ak12.Tiger_AK12_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.tiger_ak12.Tiger_AK12_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.tiger_ak12.Tiger_AK12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AK12')
   Skins(49)=(Id=3051,MIC_1P=("WEP_SkinSet01_MAT.tiger_ak12.Tiger_AK12_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.tiger_ak12.Tiger_AK12_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.tiger_ak12.Tiger_AK12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AK12')
   Skins(50)=(Id=3050,MIC_1P=("WEP_SkinSet01_MAT.tiger_ak12.Tiger_AK12_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.tiger_ak12.Tiger_AK12_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.tiger_ak12.Tiger_AK12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AK12')
   Skins(51)=(Id=3055,MIC_1P=("WEP_SkinSet01_MAT.skullcracker_pulverizer.SkullCracker_Pulverizer_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.skullcracker_pulverizer.SkullCracker_Pulverizer_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.skullcracker_pulverizer.SkullCracker_Pulverizer_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Pulverizer')
   Skins(52)=(Id=3054,MIC_1P=("WEP_SkinSet01_MAT.skullcracker_pulverizer.SkullCracker_Pulverizer_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.skullcracker_pulverizer.SkullCracker_Pulverizer_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.skullcracker_pulverizer.SkullCracker_Pulverizer_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Pulverizer')
   Skins(53)=(Id=3053,MIC_1P=("WEP_SkinSet01_MAT.skullcracker_pulverizer.SkullCracker_Pulverizer_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.skullcracker_pulverizer.SkullCracker_Pulverizer_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.skullcracker_pulverizer.SkullCracker_Pulverizer_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Pulverizer')
   Skins(54)=(Id=3058,MIC_1P=("WEP_SkinSet01_MAT.fleshpounder_aa12.Fleshpounder_AA12_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.fleshpounder_aa12.Fleshpounder_AA12_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.fleshpounder_aa12.Fleshpounder_AA12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AA12')
   Skins(55)=(Id=3057,MIC_1P=("WEP_SkinSet01_MAT.fleshpounder_aa12.Fleshpounder_AA12_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.fleshpounder_aa12.Fleshpounder_AA12_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.fleshpounder_aa12.Fleshpounder_AA12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AA12')
   Skins(56)=(Id=3056,MIC_1P=("WEP_SkinSet01_MAT.fleshpounder_aa12.Fleshpounder_AA12_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.fleshpounder_aa12.Fleshpounder_AA12_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.fleshpounder_aa12.Fleshpounder_AA12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AA12')
   Skins(57)=(Id=3064,MIC_1P=("WEP_SkinSet01_MAT.horzineeliteblue_scar.HorzineEliteBlue_SCAR_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.horzineeliteblue_scar.HorzineEliteBlue_SCAR_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.horzineeliteblue_scar.HorzineEliteBlue_SCAR_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_SCAR')
   Skins(58)=(Id=3063,MIC_1P=("WEP_SkinSet01_MAT.horzineeliteblue_scar.HorzineEliteBlue_SCAR_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.horzineeliteblue_scar.HorzineEliteBlue_SCAR_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.horzineeliteblue_scar.HorzineEliteBlue_SCAR_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_SCAR')
   Skins(59)=(Id=3062,MIC_1P=("WEP_SkinSet01_MAT.horzineeliteblue_scar.HorzineEliteBlue_SCAR_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.horzineeliteblue_scar.HorzineEliteBlue_SCAR_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.horzineeliteblue_scar.HorzineEliteBlue_SCAR_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_SCAR')
   Skins(60)=(Id=3061,MIC_1P=("WEP_SkinSet01_MAT.horzineelitered_scar.HorzineEliteRed_SCAR_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.horzineelitered_scar.HorzineEliteRed_SCAR_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.horzineelitered_scar.HorzineEliteRed_SCAR_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_SCAR')
   Skins(61)=(Id=3060,MIC_1P=("WEP_SkinSet01_MAT.horzineelitered_scar.HorzineEliteRed_SCAR_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.horzineelitered_scar.HorzineEliteRed_SCAR_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.horzineelitered_scar.HorzineEliteRed_SCAR_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_SCAR')
   Skins(62)=(Id=3059,MIC_1P=("WEP_SkinSet01_MAT.horzineelitered_scar.HorzineEliteRed_SCAR_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.horzineelitered_scar.HorzineEliteRed_SCAR_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.horzineelitered_scar.HorzineEliteRed_SCAR_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_SCAR')
   Skins(63)=(Id=3070,MIC_1P=("WEP_SkinSet01_MAT.cyberbone_katana.CyberBone_Katana_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.cyberbone_katana.CyberBone_Katana_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.cyberbone_katana.CyberBone_Katana_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Katana')
   Skins(64)=(Id=3069,MIC_1P=("WEP_SkinSet01_MAT.cyberbone_katana.CyberBone_Katana_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.cyberbone_katana.CyberBone_Katana_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.cyberbone_katana.CyberBone_Katana_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Katana')
   Skins(65)=(Id=3068,MIC_1P=("WEP_SkinSet01_MAT.cyberbone_katana.CyberBone_Katana_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.cyberbone_katana.CyberBone_Katana_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.cyberbone_katana.CyberBone_Katana_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Katana')
   Skins(66)=(Id=3076,MIC_1P=("WEP_SkinSet01_MAT.cyberbone_aa12.CyberBone_AA12_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.cyberbone_aa12.CyberBone_AA12_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.cyberbone_aa12.CyberBone_AA12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AA12')
   Skins(67)=(Id=3075,MIC_1P=("WEP_SkinSet01_MAT.cyberbone_aa12.CyberBone_AA12_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.cyberbone_aa12.CyberBone_AA12_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.cyberbone_aa12.CyberBone_AA12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AA12')
   Skins(68)=(Id=3074,MIC_1P=("WEP_SkinSet01_MAT.cyberbone_aa12.CyberBone_AA12_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.cyberbone_aa12.CyberBone_AA12_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.cyberbone_aa12.CyberBone_AA12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AA12')
   Skins(69)=(Id=3073,MIC_1P=("WEP_SkinSet01_MAT.cyberbone_ak12.CyberBone_AK12_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.cyberbone_ak12.CyberBone_AK12_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.cyberbone_ak12.CyberBone_AK12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AK12')
   Skins(70)=(Id=3072,MIC_1P=("WEP_SkinSet01_MAT.cyberbone_ak12.CyberBone_AK12_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.cyberbone_ak12.CyberBone_AK12_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.cyberbone_ak12.CyberBone_AK12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AK12')
   Skins(71)=(Id=3071,MIC_1P=("WEP_SkinSet01_MAT.cyberbone_ak12.CyberBone_AK12_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.cyberbone_ak12.CyberBone_AK12_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.cyberbone_ak12.CyberBone_AK12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AK12')
   Skins(72)=(Id=3079,MIC_1P=("WEP_SkinSet01_MAT.cyberbone_ar15.CyberBone_AR15_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.cyberbone_ar15.CyberBone_AR15_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.cyberbone_ar15.CyberBone_AR15_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AR15')
   Skins(73)=(Id=3078,MIC_1P=("WEP_SkinSet01_MAT.cyberbone_ar15.CyberBone_AR15_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.cyberbone_ar15.CyberBone_AR15_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.cyberbone_ar15.CyberBone_AR15_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AR15')
   Skins(74)=(Id=3077,MIC_1P=("WEP_SkinSet01_MAT.cyberbone_ar15.CyberBone_AR15_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.cyberbone_ar15.CyberBone_AR15_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.cyberbone_ar15.CyberBone_AR15_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AR15')
   Skins(75)=(Id=3344,MIC_1P=("WEP_SkinSet01_MAT.cyberbone_supportknife.CyberBone_SupportKnife_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.cyberbone_supportknife.CyberBone_SupportKnife_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.cyberbone_supportknife.CyberBone_SupportKnife_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Knife_Support')
   Skins(76)=(Id=3343,MIC_1P=("WEP_SkinSet01_MAT.cyberbone_supportknife.CyberBone_SupportKnife_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.cyberbone_supportknife.CyberBone_SupportKnife_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.cyberbone_supportknife.CyberBone_SupportKnife_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Knife_Support')
   Skins(77)=(Id=3342,MIC_1P=("WEP_SkinSet01_MAT.cyberbone_supportknife.CyberBone_SupportKnife_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.cyberbone_supportknife.CyberBone_SupportKnife_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.cyberbone_supportknife.CyberBone_SupportKnife_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Knife_Support')
   Skins(78)=(Id=3094,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_aa12.StoriesOfWar_AA12_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_aa12.StoriesOfWar_AA12_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_aa12.StoriesOfWar_AA12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AA12')
   Skins(79)=(Id=3093,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_aa12.StoriesOfWar_AA12_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_aa12.StoriesOfWar_AA12_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_aa12.StoriesOfWar_AA12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AA12')
   Skins(80)=(Id=3092,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_aa12.StoriesOfWar_AA12_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_aa12.StoriesOfWar_AA12_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_aa12.StoriesOfWar_AA12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AA12')
   Skins(81)=(Id=3112,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_ak12.StoriesOfWar_AK12_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_ak12.StoriesOfWar_AK12_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_ak12.StoriesOfWar_AK12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AK12')
   Skins(82)=(Id=3111,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_ak12.StoriesOfWar_AK12_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_ak12.StoriesOfWar_AK12_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_ak12.StoriesOfWar_AK12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AK12')
   Skins(83)=(Id=3110,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_ak12.StoriesOfWar_AK12_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_ak12.StoriesOfWar_AK12_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_ak12.StoriesOfWar_AK12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AK12')
   Skins(84)=(Id=3088,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_dragonsbreath.StoriesOfWar_DragonsBreath_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_dragonsbreath.StoriesOfWar_DragonsBreath_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_dragonsbreath.StoriesOfWar_DragonsBreath_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_DragonsBreath')
   Skins(85)=(Id=3087,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_dragonsbreath.StoriesOfWar_DragonsBreath_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_dragonsbreath.StoriesOfWar_DragonsBreath_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_dragonsbreath.StoriesOfWar_DragonsBreath_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_DragonsBreath')
   Skins(86)=(Id=3086,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_dragonsbreath.StoriesOfWar_DragonsBreath_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_dragonsbreath.StoriesOfWar_DragonsBreath_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_dragonsbreath.StoriesOfWar_DragonsBreath_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_DragonsBreath')
   Skins(87)=(Id=3082,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_m4.StoriesOfWar_M4_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_m4.StoriesOfWar_M4_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_m4.StoriesOfWar_M4_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_M4')
   Skins(88)=(Id=3081,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_m4.StoriesOfWar_M4_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_m4.StoriesOfWar_M4_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_m4.StoriesOfWar_M4_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_M4')
   Skins(89)=(Id=3080,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_m4.StoriesOfWar_M4_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_m4.StoriesOfWar_M4_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_m4.StoriesOfWar_M4_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_M4')
   Skins(90)=(Id=3091,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_m79.StoriesOfWar_M79_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_m79.StoriesOfWar_M79_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_m79.StoriesOfWar_M79_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_M79')
   Skins(91)=(Id=3090,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_m79.StoriesOfWar_M79_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_m79.StoriesOfWar_M79_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_m79.StoriesOfWar_M79_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_M79')
   Skins(92)=(Id=3089,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_m79.StoriesOfWar_M79_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_m79.StoriesOfWar_M79_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_m79.StoriesOfWar_M79_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_M79')
   Skins(93)=(Id=3097,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_rpg7.StoriesOfWar_RPG7_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_rpg7.StoriesOfWar_RPG7_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_rpg7.StoriesOfWar_RPG7_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_RPG7')
   Skins(94)=(Id=3096,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_rpg7.StoriesOfWar_RPG7_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_rpg7.StoriesOfWar_RPG7_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_rpg7.StoriesOfWar_RPG7_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_RPG7')
   Skins(95)=(Id=3095,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_rpg7.StoriesOfWar_RPG7_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_rpg7.StoriesOfWar_RPG7_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_rpg7.StoriesOfWar_RPG7_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_RPG7')
   Skins(96)=(Id=3085,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_scar.StoriesOfWar_SCAR_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_scar.StoriesOfWar_SCAR_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_scar.StoriesOfWar_SCAR_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_SCAR')
   Skins(97)=(Id=3084,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_scar.StoriesOfWar_SCAR_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_scar.StoriesOfWar_SCAR_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_scar.StoriesOfWar_SCAR_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_SCAR')
   Skins(98)=(Id=3083,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_scar.StoriesOfWar_SCAR_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_scar.StoriesOfWar_SCAR_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_scar.StoriesOfWar_SCAR_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_SCAR')
   Skins(99)=(Id=3100,MIC_1P=("WEP_SkinSet01_MAT.dragonfire_caulknburn.Dragonfire_CaulkNBurn_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.dragonfire_caulknburn.Dragonfire_CaulkNBurn_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.dragonfire_caulknburn.Dragonfire_CaulkNBurn_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_CaulkBurn')
   Skins(100)=(Id=3099,MIC_1P=("WEP_SkinSet01_MAT.dragonfire_caulknburn.Dragonfire_CaulkNBurn_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.dragonfire_caulknburn.Dragonfire_CaulkNBurn_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.dragonfire_caulknburn.Dragonfire_CaulkNBurn_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_CaulkBurn')
   Skins(101)=(Id=3098,MIC_1P=("WEP_SkinSet01_MAT.dragonfire_caulknburn.Dragonfire_CaulkNBurn_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.dragonfire_caulknburn.Dragonfire_CaulkNBurn_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.dragonfire_caulknburn.Dragonfire_CaulkNBurn_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_CaulkBurn')
   Skins(102)=(Id=3106,MIC_1P=("WEP_SkinSet01_MAT.dragonfire_dragonsbreath.Dragonfire_DragonsBreath_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.dragonfire_dragonsbreath.Dragonfire_DragonsBreath_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.dragonfire_dragonsbreath.Dragonfire_DragonsBreath_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_DragonsBreath')
   Skins(103)=(Id=3105,MIC_1P=("WEP_SkinSet01_MAT.dragonfire_dragonsbreath.Dragonfire_DragonsBreath_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.dragonfire_dragonsbreath.Dragonfire_DragonsBreath_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.dragonfire_dragonsbreath.Dragonfire_DragonsBreath_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_DragonsBreath')
   Skins(104)=(Id=3104,MIC_1P=("WEP_SkinSet01_MAT.dragonfire_dragonsbreath.Dragonfire_DragonsBreath_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.dragonfire_dragonsbreath.Dragonfire_DragonsBreath_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.dragonfire_dragonsbreath.Dragonfire_DragonsBreath_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_DragonsBreath')
   Skins(105)=(Id=3109,MIC_1P=("WEP_SkinSet01_MAT.dragonfire_firebugknife.Dragonfire_FirebugKnife_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.dragonfire_firebugknife.Dragonfire_FirebugKnife_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.dragonfire_firebugknife.Dragonfire_FirebugKnife_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Knife_Firebug')
   Skins(106)=(Id=3108,MIC_1P=("WEP_SkinSet01_MAT.dragonfire_firebugknife.Dragonfire_FirebugKnife_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.dragonfire_firebugknife.Dragonfire_FirebugKnife_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.dragonfire_firebugknife.Dragonfire_FirebugKnife_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Knife_Firebug')
   Skins(107)=(Id=3107,MIC_1P=("WEP_SkinSet01_MAT.dragonfire_firebugknife.Dragonfire_FirebugKnife_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.dragonfire_firebugknife.Dragonfire_FirebugKnife_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.dragonfire_firebugknife.Dragonfire_FirebugKnife_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Knife_Firebug')
   Skins(108)=(Id=3103,MIC_1P=("WEP_SkinSet01_MAT.dragonfire_flamethrower.Dragonfire_Flamethrower_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.dragonfire_flamethrower.Dragonfire_Flamethrower_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.dragonfire_flamethrower.Dragonfire_Flamethrower_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_FlameThrower')
   Skins(109)=(Id=3102,MIC_1P=("WEP_SkinSet01_MAT.dragonfire_flamethrower.Dragonfire_Flamethrower_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.dragonfire_flamethrower.Dragonfire_Flamethrower_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.dragonfire_flamethrower.Dragonfire_Flamethrower_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_FlameThrower')
   Skins(110)=(Id=3101,MIC_1P=("WEP_SkinSet01_MAT.dragonfire_flamethrower.Dragonfire_Flamethrower_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.dragonfire_flamethrower.Dragonfire_Flamethrower_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.dragonfire_flamethrower.Dragonfire_Flamethrower_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_FlameThrower')
   Skins(111)=(Id=3324,MIC_1P=("WEP_SkinSet01_MAT.thepeacemaker_m79.ThePeacemaker_M79_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.thepeacemaker_m79.ThePeacemaker_M79_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.thepeacemaker_m79.ThePeacemaker_M79_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_M79')
   Skins(112)=(Id=3323,MIC_1P=("WEP_SkinSet01_MAT.thepeacemaker_m79.ThePeacemaker_M79_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.thepeacemaker_m79.ThePeacemaker_M79_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.thepeacemaker_m79.ThePeacemaker_M79_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_M79')
   Skins(113)=(Id=3322,MIC_1P=("WEP_SkinSet01_MAT.thepeacemaker_m79.ThePeacemaker_M79_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.thepeacemaker_m79.ThePeacemaker_M79_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.thepeacemaker_m79.ThePeacemaker_M79_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_M79')
   Skins(114)=(Id=3067,MIC_1P=("WEP_SkinSet01_MAT.rusteddeath_mb500.RustedDeath_MB500_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.rusteddeath_mb500.RustedDeath_MB500_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.rusteddeath_mb500.RustedDeath_MB500_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_MB500')
   Skins(115)=(Id=3066,MIC_1P=("WEP_SkinSet01_MAT.rusteddeath_mb500.RustedDeath_MB500_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.rusteddeath_mb500.RustedDeath_MB500_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.rusteddeath_mb500.RustedDeath_MB500_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_MB500')
   Skins(116)=(Id=3065,MIC_1P=("WEP_SkinSet01_MAT.rusteddeath_mb500.RustedDeath_MB500_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.rusteddeath_mb500.RustedDeath_MB500_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.rusteddeath_mb500.RustedDeath_MB500_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_MB500')
   Skins(117)=(Id=3347,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_ar15.StoriesOfWar_AR15_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_ar15.StoriesOfWar_AR15_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_ar15.StoriesOfWar_AR15_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AR15')
   Skins(118)=(Id=3346,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_ar15.StoriesOfWar_AR15_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_ar15.StoriesOfWar_AR15_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_ar15.StoriesOfWar_AR15_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AR15')
   Skins(119)=(Id=3345,MIC_1P=("WEP_SkinSet01_MAT.storiesofwar_ar15.StoriesOfWar_AR15_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.storiesofwar_ar15.StoriesOfWar_AR15_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.storiesofwar_ar15.StoriesOfWar_AR15_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AR15')
   Skins(120)=(Id=3269,MIC_1P=("WEP_SkinSet01_MAT.containment_ar15.Containment_AR15_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.containment_ar15.Containment_AR15_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.containment_ar15.Containment_AR15_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AR15')
   Skins(121)=(Id=3268,MIC_1P=("WEP_SkinSet01_MAT.containment_ar15.Containment_AR15_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.containment_ar15.Containment_AR15_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.containment_ar15.Containment_AR15_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AR15')
   Skins(122)=(Id=3267,MIC_1P=("WEP_SkinSet01_MAT.containment_ar15.Containment_AR15_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.containment_ar15.Containment_AR15_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.containment_ar15.Containment_AR15_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AR15')
   Skins(123)=(Id=3272,MIC_1P=("WEP_SkinSet01_MAT.putridbile_m79.PutridBile_M79_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.putridbile_m79.PutridBile_M79_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.putridbile_m79.PutridBile_M79_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_M79')
   Skins(124)=(Id=3271,MIC_1P=("WEP_SkinSet01_MAT.putridbile_m79.PutridBile_M79_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.putridbile_m79.PutridBile_M79_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.putridbile_m79.PutridBile_M79_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_M79')
   Skins(125)=(Id=3270,MIC_1P=("WEP_SkinSet01_MAT.putridbile_m79.PutridBile_M79_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.putridbile_m79.PutridBile_M79_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.putridbile_m79.PutridBile_M79_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_M79')
   Skins(126)=(Id=3296,MIC_1P=("WEP_SkinSet01_MAT.heat_dragonsbreath.Heat_DragonsBreath_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.heat_dragonsbreath.Heat_DragonsBreath_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.heat_dragonsbreath.Heat_DragonsBreath_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_DragonsBreath')
   Skins(127)=(Id=3295,MIC_1P=("WEP_SkinSet01_MAT.heat_dragonsbreath.Heat_DragonsBreath_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.heat_dragonsbreath.Heat_DragonsBreath_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.heat_dragonsbreath.Heat_DragonsBreath_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_DragonsBreath')
   Skins(128)=(Id=3294,MIC_1P=("WEP_SkinSet01_MAT.heat_dragonsbreath.Heat_DragonsBreath_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.heat_dragonsbreath.Heat_DragonsBreath_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.heat_dragonsbreath.Heat_DragonsBreath_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_DragonsBreath')
   Skins(129)=(Id=3299,MIC_1P=("WEP_SkinSet01_MAT.heat_doublebarrel.Heat_DoubleBarrel_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_MAT.heat_doublebarrel.Heat_DoubleBarrel_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_MAT.heat_doublebarrel.Heat_DoubleBarrel_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_DoubleBarrel')
   Skins(130)=(Id=3298,MIC_1P=("WEP_SkinSet01_MAT.heat_doublebarrel.Heat_DoubleBarrel_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet01_MAT.heat_doublebarrel.Heat_DoubleBarrel_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet01_MAT.heat_doublebarrel.Heat_DoubleBarrel_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_DoubleBarrel')
   Skins(131)=(Id=3297,MIC_1P=("WEP_SkinSet01_MAT.heat_doublebarrel.Heat_DoubleBarrel_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet01_MAT.heat_doublebarrel.Heat_DoubleBarrel_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet01_MAT.heat_doublebarrel.Heat_DoubleBarrel_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_DoubleBarrel')
   Skins(132)=(Id=3289,MIC_1P=("WEP_SkinSet01_P01_MAT.precious_ar15.Precious_AR15_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_P01_MAT.precious_ar15.Precious_AR15_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_P01_MAT.precious_ar15.Precious_AR15_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AR15')
   Skins(133)=(Id=3290,MIC_1P=("WEP_SkinSet01_P01_MAT.precious_caulknburn.Precious_CaulkNBurn_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_P01_MAT.precious_caulknburn.Precious_CaulkNBurn_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_P01_MAT.precious_caulknburn.Precious_CaulkNBurn_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_CaulkBurn')
   Skins(134)=(Id=3291,MIC_1P=("WEP_SkinSet01_P01_MAT.precious_crovel.Precious_Crovel_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_P01_MAT.precious_crovel.Precious_Crovel_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_P01_MAT.precious_crovel.Precious_Crovel_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Crovel')
   Skins(135)=(Id=3292,MIC_1P=("WEP_SkinSet01_P01_MAT.precious_hx25.Precious_HX25_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_P01_MAT.precious_hx25.Precious_HX25_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_P01_MAT.precious_hx25.Precious_HX25_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_HX25')
   Skins(136)=(Id=3293,MIC_1P=("WEP_SkinSet01_P01_MAT.precious_mb500.Precious_MB500_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_P01_MAT.precious_mb500.Precious_MB500_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_P01_MAT.precious_mb500.Precious_MB500_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_MB500')
   Skins(137)=(Id=3335,MIC_1P=("WEP_SkinSet01_P01_MAT.precious_medicpistol.Precious_MedicPistol_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_P01_MAT.precious_medicpistol.Precious_MedicPistol_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_P01_MAT.precious_medicpistol.Precious_MedicPistol_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_MedicPistol')
   Skins(138)=(Id=3303,MIC_1P=("WEP_SkinSet01_P01_MAT.precious_remington1858.Precious_Remington_1858_1P_Mint_MIC"),MIC_3P="WEP_SkinSet01_P01_MAT.precious_remington1858.Precious_Remington_1858_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet01_P01_MAT.precious_remington1858.Precious_Remington_1858_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Remington1858')
   Skins(139)=(Id=3306,MIC_1P=("WEP_SkinSet02_MAT.bloodcamo_remington1858.BloodCamo_Remington1858_1P_Mint_MIC"),MIC_3P="WEP_SkinSet02_MAT.bloodcamo_remington1858.BloodCamo_Remington1858_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet02_MAT.bloodcamo_remington1858.BloodCamo_Remington1858_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Remington1858')
   Skins(140)=(Id=3305,MIC_1P=("WEP_SkinSet02_MAT.bloodcamo_remington1858.BloodCamo_Remington1858_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet02_MAT.bloodcamo_remington1858.BloodCamo_Remington1858_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet02_MAT.bloodcamo_remington1858.BloodCamo_Remington1858_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Remington1858')
   Skins(141)=(Id=3304,MIC_1P=("WEP_SkinSet02_MAT.bloodcamo_remington1858.BloodCamo_Remington1858_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet02_MAT.bloodcamo_remington1858.BloodCamo_Remington1858_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet02_MAT.bloodcamo_remington1858.BloodCamo_Remington1858_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Remington1858')
   Skins(142)=(Id=3309,MIC_1P=("WEP_SkinSet02_MAT.constitution_remington1858.Constitution_Remington1858_1P_Mint_MIC"),MIC_3P="WEP_SkinSet02_MAT.constitution_remington1858.Constitution_Remington1858_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet02_MAT.constitution_remington1858.Constitution_Remington1858_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Remington1858')
   Skins(143)=(Id=3308,MIC_1P=("WEP_SkinSet02_MAT.constitution_remington1858.Constitution_Remington1858_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet02_MAT.constitution_remington1858.Constitution_Remington1858_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet02_MAT.constitution_remington1858.Constitution_Remington1858_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Remington1858')
   Skins(144)=(Id=3307,MIC_1P=("WEP_SkinSet02_MAT.constitution_remington1858.Constitution_Remington1858_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet02_MAT.constitution_remington1858.Constitution_Remington1858_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet02_MAT.constitution_remington1858.Constitution_Remington1858_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Remington1858')
   Skins(145)=(Id=3312,MIC_1P=("WEP_SkinSet02_MAT.dosh_mb500.Dosh_MB500_1P_Mint_MIC"),MIC_3P="WEP_SkinSet02_MAT.dosh_mb500.Dosh_MB500_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet02_MAT.dosh_mb500.Dosh_MB500_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_MB500')
   Skins(146)=(Id=3311,MIC_1P=("WEP_SkinSet02_MAT.dosh_mb500.Dosh_MB500_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet02_MAT.dosh_mb500.Dosh_MB500_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet02_MAT.dosh_mb500.Dosh_MB500_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_MB500')
   Skins(147)=(Id=3310,MIC_1P=("WEP_SkinSet02_MAT.dosh_mb500.Dosh_MB500_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet02_MAT.dosh_mb500.Dosh_MB500_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet02_MAT.dosh_mb500.Dosh_MB500_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_MB500')
   Skins(148)=(Id=3315,MIC_1P=("WEP_SkinSet02_MAT.dosh_l85a2.Dosh_L85A2_1P_Mint_MIC"),MIC_3P="WEP_SkinSet02_MAT.dosh_l85a2.Dosh_L85A2_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet02_MAT.dosh_l85a2.Dosh_L85A2_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Bullpup')
   Skins(149)=(Id=3314,MIC_1P=("WEP_SkinSet02_MAT.dosh_l85a2.Dosh_L85A2_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet02_MAT.dosh_l85a2.Dosh_L85A2_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet02_MAT.dosh_l85a2.Dosh_L85A2_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Bullpup')
   Skins(150)=(Id=3313,MIC_1P=("WEP_SkinSet02_MAT.dosh_l85a2.Dosh_L85A2_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet02_MAT.dosh_l85a2.Dosh_L85A2_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet02_MAT.dosh_l85a2.Dosh_L85A2_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Bullpup')
   Skins(151)=(Id=3318,MIC_1P=("WEP_SkinSet02_MAT.snakeskin_sw_500.Snakeskin_SW_1P_Mint_MIC"),MIC_3P="WEP_SkinSet02_MAT.snakeskin_sw_500.Snakeskin_SW_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet02_MAT.snakeskin_sw_500.Snakeskin_SW_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_SW500')
   Skins(152)=(Id=3317,MIC_1P=("WEP_SkinSet02_MAT.snakeskin_sw_500.Snakeskin_SW_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet02_MAT.snakeskin_sw_500.Snakeskin_SW_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet02_MAT.snakeskin_sw_500.Snakeskin_SW_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_SW500')
   Skins(153)=(Id=3316,MIC_1P=("WEP_SkinSet02_MAT.snakeskin_sw_500.Snakeskin_SW_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet02_MAT.snakeskin_sw_500.Snakeskin_SW_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet02_MAT.snakeskin_sw_500.Snakeskin_SW_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_SW500')
   Skins(154)=(Id=3321,MIC_1P=("WEP_SkinSet02_MAT.snakeskingreen_aa12.SnakeskinGreen_AA12_1P_Mint_MIC"),MIC_3P="WEP_SkinSet02_MAT.snakeskingreen_aa12.SnakeskinGreen_AA12_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet02_MAT.snakeskingreen_aa12.SnakeskinGreen_AA12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AA12')
   Skins(155)=(Id=3320,MIC_1P=("WEP_SkinSet02_MAT.snakeskingreen_aa12.SnakeskinGreen_AA12_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet02_MAT.snakeskingreen_aa12.SnakeskinGreen_AA12_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet02_MAT.snakeskingreen_aa12.SnakeskinGreen_AA12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AA12')
   Skins(156)=(Id=3319,MIC_1P=("WEP_SkinSet02_MAT.snakeskingreen_aa12.SnakeskinGreen_AA12_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet02_MAT.snakeskingreen_aa12.SnakeskinGreen_AA12_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet02_MAT.snakeskingreen_aa12.SnakeskinGreen_AA12_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_AA12')
   Skins(157)=(Id=3327,MIC_1P=("WEP_SkinSet02_MAT.circuit_hx25.Circuit_HX25_1P_Mint_MIC"),MIC_3P="WEP_SkinSet02_MAT.circuit_hx25.Circuit_HX25_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet02_MAT.circuit_hx25.Circuit_HX25_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_HX25')
   Skins(158)=(Id=3326,MIC_1P=("WEP_SkinSet02_MAT.circuit_hx25.Circuit_HX25_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet02_MAT.circuit_hx25.Circuit_HX25_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet02_MAT.circuit_hx25.Circuit_HX25_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_HX25')
   Skins(159)=(Id=3325,MIC_1P=("WEP_SkinSet02_MAT.circuit_hx25.Circuit_HX25_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet02_MAT.circuit_hx25.Circuit_HX25_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet02_MAT.circuit_hx25.Circuit_HX25_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_HX25')
   Skins(160)=(Id=3330,MIC_1P=("WEP_SkinSet02_MAT.circuitglow_hx25.CircuitGlow_HX25_1P_Mint_MIC"),MIC_3P="WEP_SkinSet02_MAT.circuitglow_hx25.CircuitGlow_HX25_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet02_MAT.circuitglow_hx25.CircuitGlow_HX25_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_HX25')
   Skins(161)=(Id=3329,MIC_1P=("WEP_SkinSet02_MAT.circuitglow_hx25.CircuitGlow_HX25_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet02_MAT.circuitglow_hx25.CircuitGlow_HX25_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet02_MAT.circuitglow_hx25.CircuitGlow_HX25_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_HX25')
   Skins(162)=(Id=3328,MIC_1P=("WEP_SkinSet02_MAT.circuitglow_hx25.CircuitGlow_HX25_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet02_MAT.circuitglow_hx25.CircuitGlow_HX25_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet02_MAT.circuitglow_hx25.CircuitGlow_HX25_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_HX25')
   Skins(163)=(Id=3333,MIC_1P=("WEP_SkinSet02_MAT.glowtext_katana.GlowText_Katana_1P_Mint_MIC"),MIC_3P="WEP_SkinSet02_MAT.glowtext_katana.GlowText_Katana_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet02_MAT.glowtext_katana.GlowText_Katana_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Katana')
   Skins(164)=(Id=3332,MIC_1P=("WEP_SkinSet02_MAT.glowtext_katana.GlowText_Katana_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet02_MAT.glowtext_katana.GlowText_Katana_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet02_MAT.glowtext_katana.GlowText_Katana_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Katana')
   Skins(165)=(Id=3331,MIC_1P=("WEP_SkinSet02_MAT.glowtext_katana.GlowText_Katana_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet02_MAT.glowtext_katana.GlowText_Katana_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet02_MAT.glowtext_katana.GlowText_Katana_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_Katana')
   Skins(166)=(Id=3338,MIC_1P=("WEP_SkinSet02_MAT.carbonfiber_medicpistol.CarbonFiber_MedicPistol_1P_Mint_MIC"),MIC_3P="WEP_SkinSet02_MAT.carbonfiber_medicpistol.CarbonFiber_MedicPistol_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet02_MAT.carbonfiber_medicpistol.CarbonFiber_MedicPistol_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_MedicPistol')
   Skins(167)=(Id=3337,MIC_1P=("WEP_SkinSet02_MAT.carbonfiber_medicpistol.CarbonFiber_MedicPistol_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet02_MAT.carbonfiber_medicpistol.CarbonFiber_MedicPistol_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet02_MAT.carbonfiber_medicpistol.CarbonFiber_MedicPistol_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_MedicPistol')
   Skins(168)=(Id=3336,MIC_1P=("WEP_SkinSet02_MAT.carbonfiber_medicpistol.CarbonFiber_MedicPistol_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet02_MAT.carbonfiber_medicpistol.CarbonFiber_MedicPistol_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet02_MAT.carbonfiber_medicpistol.CarbonFiber_MedicPistol_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_MedicPistol')
   Skins(169)=(Id=3341,MIC_1P=("WEP_SkinSet02_MAT.carbonfiber_medicpistol.CarbonFiber_MedicPistol_1P_Mint_MIC","WEP_SkinSet02_MAT.carbonfiber_medicsmg.CarbonFiber_MedicSMG_1P_Mint_MIC"),MIC_3P="WEP_SkinSet02_MAT.carbonfiber_medicsmg.CarbonFiber_MedicSMG_3P_Mint_MIC",MIC_Pickup="WEP_SkinSet02_MAT.carbonfiber_medicsmg.CarbonFiber_MedicSMG_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_MedicSMG')
   Skins(170)=(Id=3340,MIC_1P=("WEP_SkinSet02_MAT.carbonfiber_medicpistol.CarbonFiber_MedicPistol_1P_FieldTested_MIC","WEP_SkinSet02_MAT.carbonfiber_medicsmg.CarbonFiber_MedicSMG_1P_FieldTested_MIC"),MIC_3P="WEP_SkinSet02_MAT.carbonfiber_medicsmg.CarbonFiber_MedicSMG_3P_FieldTested_MIC",MIC_Pickup="WEP_SkinSet02_MAT.carbonfiber_medicsmg.CarbonFiber_MedicSMG_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_MedicSMG')
   Skins(171)=(Id=3339,MIC_1P=("WEP_SkinSet02_MAT.carbonfiber_medicpistol.CarbonFiber_MedicPistol_1P_BattleScarred_MIC","WEP_SkinSet02_MAT.carbonfiber_medicsmg.CarbonFiber_MedicSMG_1P_BattleScarred_MIC"),MIC_3P="WEP_SkinSet02_MAT.carbonfiber_medicsmg.CarbonFiber_MedicSMG_3P_BattleScarred_MIC",MIC_Pickup="WEP_SkinSet02_MAT.carbonfiber_medicsmg.CarbonFiber_MedicSMG_3P_Pickup_MIC",WeaponDef=Class'KFGame.KFWeapDef_MedicSMG')
   Name="Default__KFWeaponSkinList"
   ObjectArchetype=Object'Core.Default__Object'
}
